# Preventive maintenance schedule (generated by tools/pages.js).
# Tasks are JSON in [cal1615]HMI/pm_tasks: [{task, interval, units, reset_at}].
# Remaining = interval - (run hours now - run hours at last reset). Warning when under 10% left.
LIB = '[cal1615]HMI/pm_tasks'
RUN_TIME = '[cal1615]p01r02_batch_run_time_hrs'

def runTime():
	v = system.tag.readBlocking([RUN_TIME])[0].value
	return float(v or 0)

def _load():
	v = system.tag.readBlocking([LIB])[0].value
	try:
		return list(system.util.jsonDecode(v) or []) if v else []
	except:
		return []

def _store(tasks):
	system.tag.writeBlocking([LIB], [system.util.jsonEncode(tasks)])

def rows():
	now = runTime()
	out = []
	for t in _load():
		interval = float(t.get('interval') or 0)
		remaining = interval - (now - float(t.get('reset_at') or 0))
		color = '#FF6060' if remaining <= 0 else ('#FFFF80' if remaining < 0.1 * interval else '#00E000')
		out.append({'Task': t.get('task'), 'Remaining': {'value': int(round(remaining)), 'style': {'backgroundColor': color}},
			'Interval': int(interval), 'Units': t.get('units', 'Hours')})
	return out

def add(task, interval, units='Hours'):
	tasks = _load()
	tasks.append({'task': task, 'interval': float(interval), 'units': units, 'reset_at': runTime()})
	_store(tasks)

def update(index, task, interval, units='Hours'):
	tasks = _load()
	if 0 <= index < len(tasks):
		tasks[index].update({'task': task, 'interval': float(interval), 'units': units})
		_store(tasks)

def delete(index):
	tasks = _load()
	if 0 <= index < len(tasks):
		tasks.pop(index)
		_store(tasks)

def reset(index):
	tasks = _load()
	if 0 <= index < len(tasks):
		tasks[index]['reset_at'] = runTime()
		_store(tasks)
