SELECT name AS "name",
	zone_1__recirc_sp AS "zone_1__recirc_sp",
	zone_1__exhaust_sp AS "zone_1__exhaust_sp",
	zone_1__temp_sp AS "zone_1__temp_sp",
	zone_2__recirc_sp AS "zone_2__recirc_sp",
	zone_2__exhaust_sp AS "zone_2__exhaust_sp",
	zone_2__temp_sp AS "zone_2__temp_sp",
	zone_3__recirc_sp AS "zone_3__recirc_sp",
	zone_3__exhaust_sp AS "zone_3__exhaust_sp",
	zone_3__temp_sp AS "zone_3__temp_sp",
	line_speed_sp AS "line_speed_sp",
	letoff_tension_sp AS "letoff_tension_sp",
	acc_tension_sp AS "acc_tension_sp",
	acc_fill_pressure_sp AS "acc_fill_pressure_sp",
	acc_counter_pressure_sp AS "acc_counter_pressure_sp",
	cure_time_sp AS "cure_time_sp",
	platen_temp_sp AS "platen_temp_sp",
	impreg_gap_sp AS "impreg_gap_sp",
	impreg_gap_ds_offset_sp AS "impreg_gap_ds_offset_sp",
	impreg_gap_os_offset_sp AS "impreg_gap_os_offset_sp",
	impreg_supply_speed_sp AS "impreg_supply_speed_sp",
	ts1_mode_sp AS "ts1_mode_sp",
	ts1_tension_sp AS "ts1_tension_sp",
	ts1_stretch_sp AS "ts1_stretch_sp",
	slitter_speed_sp AS "slitter_speed_sp",
	adv_cooling_temp_sp AS "adv_cooling_temp_sp",
	ts2_tension_sp AS "ts2_tension_sp",
	lower_poly_tension_sp AS "lower_poly_tension_sp",
	lower_poly_b_tension_sp AS "lower_poly_b_tension_sp",
	upper_poly_tension_sp AS "upper_poly_tension_sp",
	upper_poly_b_tension_sp AS "upper_poly_b_tension_sp",
	winder_tension_sp AS "winder_tension_sp",
	winder_mode_sp AS "winder_mode_sp",
	winder_torque_sp AS "winder_torque_sp",
	tension_deviation_sp AS "tension_deviation_sp"
FROM rcp_cal1615
WHERE name = :name
