SELECT name AS "name",
	CAST(zone_1__recirc_sp AS NUMBER) AS "zone_1__recirc_sp",
	CAST(zone_1__exhaust_sp AS NUMBER) AS "zone_1__exhaust_sp",
	CAST(zone_1__temp_sp AS NUMBER) AS "zone_1__temp_sp",
	CAST(zone_2__recirc_sp AS NUMBER) AS "zone_2__recirc_sp",
	CAST(zone_2__exhaust_sp AS NUMBER) AS "zone_2__exhaust_sp",
	CAST(zone_2__temp_sp AS NUMBER) AS "zone_2__temp_sp",
	CAST(zone_3__recirc_sp AS NUMBER) AS "zone_3__recirc_sp",
	CAST(zone_3__exhaust_sp AS NUMBER) AS "zone_3__exhaust_sp",
	CAST(zone_3__temp_sp AS NUMBER) AS "zone_3__temp_sp",
	CAST(line_speed_sp AS NUMBER) AS "line_speed_sp",
	CAST(letoff_tension_sp AS NUMBER) AS "letoff_tension_sp",
	CAST(acc_tension_sp AS NUMBER) AS "acc_tension_sp",
	CAST(acc_fill_pressure_sp AS NUMBER) AS "acc_fill_pressure_sp",
	CAST(acc_counter_pressure_sp AS NUMBER) AS "acc_counter_pressure_sp",
	CAST(cure_time_sp AS NUMBER) AS "cure_time_sp",
	CAST(platen_temp_sp AS NUMBER) AS "platen_temp_sp",
	CAST(impreg_gap_sp AS NUMBER) AS "impreg_gap_sp",
	CAST(impreg_gap_ds_offset_sp AS NUMBER) AS "impreg_gap_ds_offset_sp",
	CAST(impreg_gap_os_offset_sp AS NUMBER) AS "impreg_gap_os_offset_sp",
	CAST(impreg_supply_speed_sp AS NUMBER) AS "impreg_supply_speed_sp",
	CAST(ts1_mode_sp AS NUMBER) AS "ts1_mode_sp",
	CAST(ts1_tension_sp AS NUMBER) AS "ts1_tension_sp",
	CAST(ts1_stretch_sp AS NUMBER) AS "ts1_stretch_sp",
	CAST(slitter_speed_sp AS NUMBER) AS "slitter_speed_sp",
	CAST(adv_cooling_temp_sp AS NUMBER) AS "adv_cooling_temp_sp",
	CAST(ts2_tension_sp AS NUMBER) AS "ts2_tension_sp",
	CAST(lower_poly_tension_sp AS NUMBER) AS "lower_poly_tension_sp",
	CAST(lower_poly_b_tension_sp AS NUMBER) AS "lower_poly_b_tension_sp",
	CAST(upper_poly_tension_sp AS NUMBER) AS "upper_poly_tension_sp",
	CAST(upper_poly_b_tension_sp AS NUMBER) AS "upper_poly_b_tension_sp",
	CAST(winder_tension_sp AS NUMBER) AS "winder_tension_sp",
	CAST(winder_mode_sp AS NUMBER) AS "winder_mode_sp",
	CAST(winder_torque_sp AS NUMBER) AS "winder_torque_sp",
	CAST(tension_deviation_sp AS NUMBER) AS "tension_deviation_sp"
FROM rcp_cal1615
WHERE name = :name
