-- cal1615 recipe table (database connection "myOracle", Oracle XE XEPDB1, schema EB).
-- The HMI also creates it on first use via the named query "cal1615 Recipe/Create Table".
BEGIN
	EXECUTE IMMEDIATE 'CREATE TABLE rcp_cal1615 (
		id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name NVARCHAR2(100) NOT NULL UNIQUE,
		comments NVARCHAR2(255),
		zone_1__recirc_sp NUMBER,
		zone_1__exhaust_sp NUMBER,
		zone_1__temp_sp NUMBER,
		zone_2__recirc_sp NUMBER,
		zone_2__exhaust_sp NUMBER,
		zone_2__temp_sp NUMBER,
		zone_3__recirc_sp NUMBER,
		zone_3__exhaust_sp NUMBER,
		zone_3__temp_sp NUMBER,
		line_speed_sp NUMBER,
		letoff_tension_sp NUMBER,
		acc_tension_sp NUMBER,
		acc_fill_pressure_sp NUMBER,
		acc_counter_pressure_sp NUMBER,
		cure_time_sp NUMBER,
		platen_temp_sp NUMBER,
		impreg_gap_sp NUMBER,
		impreg_gap_ds_offset_sp NUMBER,
		impreg_gap_os_offset_sp NUMBER,
		impreg_supply_speed_sp NUMBER,
		ts1_mode_sp NUMBER,
		ts1_tension_sp NUMBER,
		ts1_stretch_sp NUMBER,
		slitter_speed_sp NUMBER,
		adv_cooling_temp_sp NUMBER,
		ts2_tension_sp NUMBER,
		lower_poly_tension_sp NUMBER,
		lower_poly_b_tension_sp NUMBER,
		upper_poly_tension_sp NUMBER,
		upper_poly_b_tension_sp NUMBER,
		winder_tension_sp NUMBER,
		winder_mode_sp NUMBER,
		winder_torque_sp NUMBER,
		tension_deviation_sp NUMBER,
		modified TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
	)';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE <> -955 THEN RAISE; END IF;
END;
/
