-- cal1615 recipe table (database connection "myOracle", Oracle XE XEPDB1, schema EB).
-- The HMI also creates it on first use via the named query "cal1615 Recipe/Create Table".
BEGIN
	EXECUTE IMMEDIATE 'CREATE TABLE rcp_cal1615 (
		id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name NVARCHAR2(100) NOT NULL UNIQUE,
		comments NVARCHAR2(255),
		zone_1__recirc_sp BINARY_DOUBLE,
		zone_1__exhaust_sp BINARY_DOUBLE,
		zone_1__temp_sp BINARY_DOUBLE,
		zone_2__recirc_sp BINARY_DOUBLE,
		zone_2__exhaust_sp BINARY_DOUBLE,
		zone_2__temp_sp BINARY_DOUBLE,
		zone_3__recirc_sp BINARY_DOUBLE,
		zone_3__exhaust_sp BINARY_DOUBLE,
		zone_3__temp_sp BINARY_DOUBLE,
		line_speed_sp BINARY_DOUBLE,
		letoff_tension_sp BINARY_DOUBLE,
		acc_tension_sp BINARY_DOUBLE,
		acc_fill_pressure_sp BINARY_DOUBLE,
		acc_counter_pressure_sp BINARY_DOUBLE,
		cure_time_sp BINARY_DOUBLE,
		platen_temp_sp BINARY_DOUBLE,
		impreg_gap_sp BINARY_DOUBLE,
		impreg_gap_ds_offset_sp BINARY_DOUBLE,
		impreg_gap_os_offset_sp BINARY_DOUBLE,
		impreg_supply_speed_sp BINARY_DOUBLE,
		ts1_mode_sp BINARY_DOUBLE,
		ts1_tension_sp BINARY_DOUBLE,
		ts1_stretch_sp BINARY_DOUBLE,
		slitter_speed_sp BINARY_DOUBLE,
		adv_cooling_temp_sp BINARY_DOUBLE,
		ts2_tension_sp BINARY_DOUBLE,
		lower_poly_tension_sp BINARY_DOUBLE,
		lower_poly_b_tension_sp BINARY_DOUBLE,
		upper_poly_tension_sp BINARY_DOUBLE,
		upper_poly_b_tension_sp BINARY_DOUBLE,
		winder_tension_sp BINARY_DOUBLE,
		winder_mode_sp BINARY_DOUBLE,
		winder_torque_sp BINARY_DOUBLE,
		tension_deviation_sp BINARY_DOUBLE,
		modified TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
	)';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE <> -955 THEN RAISE; END IF;
END;
/
