# cal1615 line state: the four-state panel on the Overview. Runs on the gateway once a second (expression tag [cal1615]HMI/line_tick,
# now(1000), valueChanged), with no page open. Source of the tag script (tools/line_state.js indents it into the tag) and of the test
# (tools/line_state_test.py).
#
#   RUNNING  the line is running (p01r13_line_running)
#   DOWN     not running and a fault exists (p01r02_fault_exists: the PLC fault word is not zero)
#   SETUP    not running, no fault, and an oven zone is heating up or cooling down (status 3..9, 11, 12)
#   IDLE     anything else (ready, waiting)
# A new state must hold for DEBOUNCE_S before it counts, so a flicker does not make a state change. Every change is logged in
# LINE_STATE_LOG (myOracle); the share of the last 8 hours per state is published once a minute.
# Published: [cal1615]HMI/LineState/state, since (when the state began), pct_running, pct_idle, pct_setup, pct_down.
import sys

DB = 'myOracle'
P = '[cal1615]'
T_RUN, T_FAULT = P + 'p01r13_line_running', P + 'p01r02_fault_exists'
T_ZONES = [P + 'p11r20_status', P + 'p12r20_status', P + 'p13r20_status']
H = P + 'HMI/LineState/'
STATES = ('RUNNING', 'IDLE', 'SETUP', 'DOWN')
SETUP_CODES = (3, 4, 5, 6, 7, 8, 9, 11, 12)   # Start Recirc .. Heat to SP, Cooldown, Cooldown Fans (cal1615.tunerun.STATUS_NAMES)
DEBOUNCE_S = 3.0
WINDOW_H = 8

GL = system.util.getGlobals()
log = system.util.getLogger('cal1615.linestate')
st = GL.get('cal1615_linestate')
if st is None:
	st = {'busy': False, 'ready': False, 'state': None, 'since_ms': None, 'cand': None, 'cand_ms': 0, 't_pct': 0, 'shown': {}, 'warned': 0}
	GL['cal1615_linestate'] = st


def err(msg):
	"""One error line a minute at most (a database outage must not fill the log)."""
	now = system.date.now().getTime()
	if now - st['warned'] >= 60000:
		st['warned'] = now
		log.error(msg)


def ensure_db():
	if st['ready']:
		return
	sql = 'CREATE TABLE LINE_STATE_LOG (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, state VARCHAR2(10), start_ts TIMESTAMP DEFAULT SYSTIMESTAMP, end_ts TIMESTAMP)'
	system.db.runUpdateQuery("BEGIN EXECUTE IMMEDIATE '" + sql + "'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;", DB)
	st['ready'] = True


def classify(run, fault, zones):
	if run:
		return 'RUNNING'
	if fault:
		return 'DOWN'
	for z in zones:
		if z in SETUP_CODES:
			return 'SETUP'
	return 'IDLE'


def restore(now):
	"""After a gateway restart: carry on with the state that is still open in the log."""
	try:
		ds = system.db.runPrepQuery('SELECT state AS "state", (CAST(SYSTIMESTAMP AS DATE) - CAST(start_ts AS DATE)) * 86400 AS "age" FROM LINE_STATE_LOG WHERE end_ts IS NULL ORDER BY id DESC FETCH FIRST 1 ROWS ONLY', [], DB)
		if ds.getRowCount() > 0 and ds[0]['state'] in STATES:
			st['state'], st['since_ms'] = ds[0]['state'], now - int(float(ds[0]['age'] or 0.0) * 1000.0)
	except:
		err('Could not read LINE_STATE_LOG: %s' % sys.exc_info()[1])


def change(new, since_ms):
	back = max(0.0, (system.date.now().getTime() - since_ms) / 1000.0)    # the new state began this long ago (the debounce delay)
	try:
		system.db.runPrepUpdate("UPDATE LINE_STATE_LOG SET end_ts = SYSTIMESTAMP - NUMTODSINTERVAL(?, 'SECOND') WHERE end_ts IS NULL", [back], DB)
		system.db.runPrepUpdate("INSERT INTO LINE_STATE_LOG (state, start_ts) VALUES (?, SYSTIMESTAMP - NUMTODSINTERVAL(?, 'SECOND'))", [new, back], DB)
	except:
		err('Could not write LINE_STATE_LOG: %s' % sys.exc_info()[1])
	log.info('Line state %s -> %s' % (st['state'], new))
	st['state'], st['since_ms'] = new, since_ms


def shares():
	"""Seconds per state over the last WINDOW_H hours, as percentages."""
	try:
		ds = system.db.runPrepQuery('SELECT state AS "state", SUM((CAST(LEAST(NVL(end_ts, SYSTIMESTAMP), SYSTIMESTAMP) AS DATE) - CAST(GREATEST(start_ts, SYSTIMESTAMP - NUMTODSINTERVAL(?, \'HOUR\')) AS DATE)) * 86400) AS "secs" FROM LINE_STATE_LOG WHERE NVL(end_ts, SYSTIMESTAMP) > SYSTIMESTAMP - NUMTODSINTERVAL(?, \'HOUR\') GROUP BY state', [WINDOW_H, WINDOW_H], DB)
	except:
		err('Could not read the state shares: %s' % sys.exc_info()[1])
		return None
	secs = dict((s, 0.0) for s in STATES)
	for r in ds:
		if r['state'] in secs:
			secs[r['state']] = max(float(r['secs'] or 0.0), 0.0)
	tot = sum(secs.values())
	return dict((s, (100.0 * secs[s] / tot if tot > 0 else 0.0)) for s in STATES)


def publish(now):
	want = {'state': st['state'], 'since': system.date.fromMillis(st['since_ms'])}
	if now - st['t_pct'] >= 60000 or 'pct_running' not in st['shown']:
		st['t_pct'] = now
		sh = shares()
		if sh is not None:
			for s in STATES:
				want['pct_' + s.lower()] = round(sh[s], 1)
	chg = [k for k in want if st['shown'].get(k) != want[k]]
	if chg:
		try:
			system.tag.writeBlocking([H + k for k in chg], [want[k] for k in chg])
			for k in chg:
				st['shown'][k] = want[k]
		except:
			err('Could not publish the line state: %s' % sys.exc_info()[1])


def run():
	now = system.date.now().getTime()
	if not st['ready']:
		ensure_db()
		restore(now)
	paths = [T_RUN, T_FAULT] + T_ZONES
	rs = system.tag.readBlocking(paths)
	if not rs[0].quality.isGood() or rs[0].value is None:
		return                               # the run bit is unknown: change nothing
	vals = [r.value if r.quality.isGood() else None for r in rs]
	cand = classify(bool(vals[0]), bool(vals[1]), [v for v in vals[2:] if v is not None])
	if st['state'] is None:
		change(cand, now)                    # first ever state
	elif cand != st['state']:
		if st['cand'] != cand:
			st['cand'], st['cand_ms'] = cand, now
		if now - st['cand_ms'] >= DEBOUNCE_S * 1000.0:
			change(cand, st['cand_ms'])
			st['cand'] = None
	else:
		st['cand'] = None
	publish(now)


if not st['busy']:
	st['busy'] = True
	try:
		run()
	except:
		log.error('Line state failed: %s' % sys.exc_info()[1])
	finally:
		st['busy'] = False
