// PID tuning for cal1615 (classic PID loops; no PLC change).
//  1. Imports cal2016's PIDE autotune faceplates (Components/PID/*) as objects only - not wired to any loop.
//  2. Project script cal1615.pid: the tunable oven loops (PV, SP, output, gain sets, valve card).
//  3. Page Maintenance/PID Tuning (route /pid-tuning): loop buttons, PV/SP + output trend, live values,
//     editable gains (written to the HMI inputs the PLC loads the PID parameters from), control-valve card.
// Run: node pid_tuning.js <folder with cal2016 Components/PID copied from the gateway>
const fs = require("fs"), path = require("path");
const R = "E:/aaa_projects/ParkTemp/1615";
const P = R + "/cal1615_std/com.inductiveautomation.perspective";
const V = P + "/views";
const C16 = process.argv[2];
const rd = (f) => JSON.parse(fs.readFileSync(f, "utf8"));
const wr = (f, o) => { fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, JSON.stringify(o, null, 2)); };
const RESOURCE = fs.readFileSync(`${V}/MainViews/Feature Views/Ovens/RTO - Large/resource.json`, "utf8");
const writeView = (vp, v) => { wr(`${V}/${vp}/view.json`, v); fs.writeFileSync(`${V}/${vp}/resource.json`, RESOURCE); };

// ------------------------------------------------------------------ 1. cal2016 autotune faceplates (objects only)
if (C16) {
  for (const name of ["PID Control", "PIDE_Tuning"]) {
    const src = path.join(C16, name);
    const v = JSON.parse(fs.readFileSync(path.join(src, "view.json"), "utf8").split("[cal2016]").join("[cal1615]"));
    v.custom = { ...(v.custom || {}), note: "Imported from cal2016 (PIDE + PIDE_AUTOTUNE). Not wired: the cal1615 PLC runs classic PID. Needs PIDE loops with PIDE_AUTOTUNE tags ([cal1615]Oven {num} {UpperLower} PID Control / PID Autotune)." };
    writeView(`Components/PID/${name}`, v);
  }
  console.log("imported cal2016 PID faceplates");
}

// ------------------------------------------------------------------ 2. loops script
const zone = (n) => `\t'zone${n}': {
\t\t'label': 'Zone ${n} Temperature', 'units': 'F',
\t\t'pv': '[cal1615]p1${n}_real_to_hmi_2_', 'sp': '[cal1615]p1${n}r30_pid_temp_sp', 'cv': '[cal1615]p1${n}_ao_cv',
\t\t'set1': 'Fast PID (heat-up)', 'set2': 'Auto PID (control)', 'gains': cal1615.zones.PATHS[${n}],
\t\t'valve_view': 'Components/Oven/Zone/Control Valve', 'valve_params': {'zone': ${n}},
\t},`;
const py = `# Tunable PID loops for the PID Tuning page (Maintenance/PID Tuning, route /pid-tuning). Generated by tools/pid_tuning.js.
# The PLC runs classic PID instructions. Gains are PLC parameters (pNN_param_pidX_*); the HMI writes them to
# p02_real_from_hmi.<section>[44..51] and the PLC loads them into the PID (KP/KI/KD/BIAS).
# Gain keys follow cal1615.zones: pid1_kp / pid1_kp_w (read / write), ... pid2_bias. An empty path hides that row.
LOOPS = {
${[1, 2, 3].map(zone).join("\n")}
\t'cooling': {
\t\t'label': 'Advanced Cooling Temperature', 'units': 'F',
\t\t'pv': '[cal1615]p19_ai_tc01', 'sp': '[cal1615]p01_recipe_active/adv_cooling_temp_sp', 'cv': '[cal1615]p19_ao_cv',
\t\t'set1': '', 'set2': 'Auto PID (control)',
\t\t'gains': {  # the P19 PID uses only the second gain set
\t\t\t'pid2_kp': '[cal1615]p19_param_pid2_kp', 'pid2_kp_w': '[cal1615]p02_real_from_hmi/adv_cooling_48_',
\t\t\t'pid2_ki': '[cal1615]p19_param_pid2_ki', 'pid2_ki_w': '[cal1615]p02_real_from_hmi/adv_cooling_49_',
\t\t\t'pid2_kd': '[cal1615]p19_param_pid2_kd', 'pid2_kd_w': '[cal1615]p02_real_from_hmi/adv_cooling_50_',
\t\t\t'pid2_bias': '[cal1615]p19_param_pid2_ff', 'pid2_bias_w': '[cal1615]p02_real_from_hmi/adv_cooling_51_',
\t\t},
\t\t'valve_view': 'Components/Oven/Roll Cooling Valve', 'valve_params': {},
\t},
}
ORDER = ['zone1', 'zone2', 'zone3', 'cooling']
GAIN_KEYS = [s + '_' + g for s in ('pid1', 'pid2') for g in ('kp', 'ki', 'kd', 'bias')]

def loop(name):
\t"""Flat dict of tag paths for one loop (missing gains -> '')."""
\tl = LOOPS.get(name) or LOOPS['zone1']
\tout = dict((k, v) for k, v in l.items() if k != 'gains')
\tfor k in GAIN_KEYS:
\t\tout[k] = l['gains'].get(k, '')
\t\tout[k + '_w'] = l['gains'].get(k + '_w', '')
\treturn out

def pens(name):
\t"""Tuning trend: PV and SP on the top plot, controller output on the bottom plot."""
\tl = LOOPS.get(name) or LOOPS['zone1']
\tsrc = 'histprov:myOracle:/drv:ignition-4d950438c38c:cal1615:/tag:'
\tdef pen(label, tag, color, plot):
\t\tst = lambda o: {'fill': {'color': color, 'opacity': o}, 'stroke': {'color': color, 'dashArray': 0, 'opacity': o, 'width': 1.5}}
\t\treturn {'axis': '', 'name': label, 'plot': plot, 'enabled': True, 'selectable': True, 'visible': True,
\t\t\t'data': {'aggregateMode': 'default', 'source': src + tag.split(']', 1)[-1].lower()},
\t\t\t'display': {'type': 'line', 'breakLine': True, 'interpolation': 'curveStepAfter' if plot else 'curveLinear', 'radius': 3,
\t\t\t\t'styles': {'normal': st(0.9), 'highlighted': st(1), 'muted': st(0.4), 'selected': st(1)}}}
\treturn [pen('PV', l['pv'], '#1F77B4', 0), pen('SP', l['sp'], '#D62728', 0), pen('Output %', l['cv'], '#2CA02C', 1)]
`;
const pyDir = R + "/cal1615_std/ignition/script-python/cal1615/pid";
fs.mkdirSync(pyDir, { recursive: true });
fs.writeFileSync(pyDir + "/code.py", py);
fs.writeFileSync(pyDir + "/resource.json", fs.readFileSync(R + "/cal1615_std/ignition/script-python/cal1615/recipes/resource.json", "utf8"));

// ------------------------------------------------------------------ 3. page
const AUTH = "{session.props.auth.authenticated}";
const ROW = { paddingLeft: "6px", paddingRight: "6px", paddingTop: "3px", paddingBottom: "3px", gap: "4px" };
const ind = (key, transforms) => ({ binding: { type: "tag", config: { fallbackDelay: 2.5, mode: "indirect", references: { 0: `{view.custom.p.${key}}` }, tagPath: "{0}", bidirectional: false }, ...(transforms ? { transforms } : {}) } });
const expr = (expression) => ({ binding: { type: "expr", config: { expression } } });
const lbl = (name, text, cls, position, propConfig, style) => ({ type: "ia.display.label", meta: { name }, position, props: { text, style: { classes: cls, ...(style || {}) } }, ...(propConfig ? { propConfig } : {}) });
const row = (name, title, middle, units, display) => ({ type: "ia.container.flex", meta: { name }, position: { basis: "28px", shrink: 0 },
  props: { direction: "row", alignItems: "stretch", style: ROW },
  children: [lbl("title", title, "cal1615/row-label", { grow: 1, basis: "0" }), middle, lbl("units", units, "cal1615/units", { basis: "34px", shrink: 0 }, units === "@" ? { "props.text": expr("{view.custom.p.units}") } : undefined)],
  ...(display ? { propConfig: { "position.display": expr(display) } } : {}) });
const fmt = (f) => [{ type: "format", formatType: "numeric", formatValue: f }];
const valueRow = (name, title, key, units, f = "#,##0.0") => row(name, title, lbl("value", "---", "cal1615/value", { basis: "100px", shrink: 0 }, { "props.text": ind(key, fmt(f)) }), units);
const exprRow = (name, title, e, units) => row(name, title, lbl("value", "---", "cal1615/value", { basis: "100px", shrink: 0 }, { "props.text": expr(e) }), units);
const gainRow = (key, title, units, f) => row(`r_${key}`, title, {
  type: "ia.input.numeric-entry-field", meta: { name: "entry" }, position: { basis: "100px", shrink: 0 },
  props: { format: f, spinner: { enabled: false }, style: { classes: "cal1615/entry" } },
  propConfig: { "props.value": ind(key), "props.enabled": expr(AUTH) },
  events: { component: { onActionPerformed: { type: "script", scope: "G", config: { script:
    `\t# Read from the PLC parameter, written to the HMI input the PLC loads it from.\n\tpath = self.view.custom.p['${key}_w']\n\tif path:\n\t\tsystem.tag.writeBlocking([path], [self.props.value])` } } } } },
  units, `len({view.custom.p.${key}}) > 0`);
const card = (name, header, rows, headerBinding) => {
  const h = 26 + rows.length * 28 + 6;
  return { type: "ia.container.flex", meta: { name }, position: { basis: `${h}px`, shrink: 0 },
    props: { direction: "column", style: { classes: "cal1615/card", paddingBottom: "4px" } },
    children: [lbl("header", header, "cal1615/card-header", { basis: "26px", shrink: 0 }, headerBinding ? { "props.text": headerBinding } : undefined), ...rows] };
};
const gainCard = (set) => ({ ...card(`gains_${set}`, "", [
  gainRow(`${set}_kp`, "Proportional Gain Kp", "", "#,##0.000"),
  gainRow(`${set}_ki`, "Integral Gain Ki", "1/s", "#,##0.000"),
  gainRow(`${set}_kd`, "Derivative Gain Kd", "s", "#,##0.000"),
  gainRow(`${set}_bias`, "Bias", "%", "#,##0.0"),
], expr(`{view.custom.p.${set === "pid1" ? "set1" : "set2"}}`)),
  propConfig: { "position.display": expr(`len({view.custom.p.${set}_kp}) > 0`) } });

const LOOP_BTNS = [["zone1", "Zone 1"], ["zone2", "Zone 2"], ["zone3", "Zone 3"], ["cooling", "Advanced Cooling"]];
const btn = (id, text) => ({ type: "ia.input.button", meta: { name: `loop_${id}` }, position: { basis: id === "cooling" ? "170px" : "110px", shrink: 0 },
  props: { text, style: { fontSize: "14px" } },
  propConfig: { "props.primary": expr(`{view.custom.loop} = '${id}'`) },
  events: { component: { onActionPerformed: { type: "script", scope: "G", config: { script: `\tself.view.custom.loop = '${id}'` } } } } });

const chart = { type: "ia.chart.powerchart", meta: { name: "trend" }, position: { grow: 1, basis: "0" },
  props: { config: { measureOfTime: "minutes", unitOfTime: 30, refreshRate: 1000, visibility: { showTagBrowser: false } },
    plots: [{ color: "var(--neutral-10)", markers: [], relativeWeight: 3, style: { classes: "" } }, { color: "var(--neutral-10)", markers: [], relativeWeight: 1, style: { classes: "" } }],
    style: { classes: "cal1615/card" } },
  propConfig: {
    "props.pens": { binding: { type: "expr", config: { expression: "{view.custom.loop}" }, transforms: [{ type: "script", code: "\treturn cal1615.pid.pens(value)" }] } },
    "props.title.text": expr("{view.custom.p.label}"),
  } };

const live = card("live", "Live", [
  valueRow("pv", "Process Value (PV)", "pv", "@"),
  valueRow("sp", "Setpoint (SP)", "sp", "@"),
  exprRow("err", "Error (PV - SP)", "if(isNull({view.custom.pvv}) || isNull({view.custom.spv}), '---', numberFormat({view.custom.pvv} - {view.custom.spv}, '#,##0.0'))", "@"),
  valueRow("cv", "Controller Output", "cv", "%"),
], expr("{view.custom.p.label}"));
const valve = { type: "ia.display.view", meta: { name: "valve" }, position: { basis: "160px", shrink: 0 },
  props: { path: "", params: {}, style: { classes: "" } },
  propConfig: { "props.path": expr("{view.custom.p.valve_view}"), "props.params": { binding: { type: "property", config: { path: "view.custom.p.valve_params" } } } } };
const note = lbl("note", "Gains are PLC parameters. A value entered here is sent to the HMI input the PLC loads the PID from; it takes effect on the next PLC scan. Trend: 30 min, history logged every 10 s.",
  "", { basis: "auto", shrink: 0 }, undefined, { fontSize: "11px", color: "var(--neutral-70)", whiteSpace: "normal", padding: "2px 4px" });

const view = {
  custom: { loop: "zone1", pvv: null, spv: null },
  params: {},
  propConfig: {
    "custom.p": { binding: { type: "expr", config: { expression: 'runScript("cal1615.pid.loop", 0, {view.custom.loop})' } } },
    "custom.pvv": ind("pv"), "custom.spv": ind("sp"),
  },
  props: { defaultSize: { width: 1680, height: 1024 } },
  root: { type: "ia.container.flex", meta: { name: "root" }, position: {}, props: { direction: "column", style: { padding: "6px", gap: "8px", overflow: "hidden" } },
    children: [
      { type: "ia.container.flex", meta: { name: "topBar" }, position: { basis: "44px", shrink: 0 }, props: { direction: "row", alignItems: "center", style: { gap: "8px" } },
        children: [lbl("title", "PID Tuning", "cal1615/page-title", { basis: "220px", shrink: 0 }, undefined, { textAlign: "left" }), ...LOOP_BTNS.map(([id, t]) => btn(id, t))] },
      { type: "ia.container.flex", meta: { name: "body" }, position: { grow: 1, basis: "0" }, props: { direction: "row", alignItems: "stretch", style: { gap: "8px" } },
        children: [chart,
          { type: "ia.container.flex", meta: { name: "side" }, position: { basis: "420px", shrink: 0 }, props: { direction: "column", style: { gap: "8px", overflowY: "auto" } },
            children: [live, gainCard("pid1"), gainCard("pid2"), valve, note] }] },
    ] },
};
writeView("MainViews/Feature Views/Maintenance/PID Tuning", view);

// ------------------------------------------------------------------ 4. navigation
const pcf = `${P}/page-config/config.json`;
const pc = rd(pcf);
pc.pages["/pid-tuning"] = { ...pc.pages["/zone-setup"], viewPath: "MainViews/Feature Views/Maintenance/PID Tuning" };
wr(pcf, pc);
const navf = `${V}/MainViews/Nav/Maintenance/view.json`;
const nav = rd(navf);
const items = nav.root.children[0].props.items;
if (!items.some((i) => i.target === "/pid-tuning")) {
  const zs = items.find((i) => i.target === "/zone-setup");
  items.splice(items.indexOf(zs) + 1, 0, { ...JSON.parse(JSON.stringify(zs)), label: { ...zs.label, text: "PID Tuning" }, target: "/pid-tuning" });
  nav.props.defaultSize.height = Math.round(nav.props.defaultSize.height * items.length / (items.length - 1));
  wr(navf, nav);
}
const hf = `${V}/Framework/Header Main Nav/view.json`;
let hs = fs.readFileSync(hf, "utf8");
if (!hs.includes('\\"/pid-tuning\\"')) { hs = hs.split('{page.props.path} = \\"/zone-setup\\"').join('{page.props.path} = \\"/zone-setup\\" || {page.props.path} = \\"/pid-tuning\\"'); fs.writeFileSync(hf, hs); }
console.log("PID Tuning page, script cal1615.pid, route /pid-tuning, Maintenance menu entry done");
