# cal1615 roll logging. Runs on the gateway every 500 ms (the expression tag [cal1615]HMI/roll_tick, now(500), valueChanged), with no
# page open. Source of the tag script (tools/roll_logging.js indents it into the tag) and of the test (tools/roll_test.py).
#
# WHAT IT DOES
#  1. Detects production: tank up and RTO permissive (plus the operator override buttons), with a winder winding.
#  2. Cuts rolls from the winder length counters (the rule is the operator's): a new roll starts when the OTHER winder starts winding
#     after both winders were stopped and its length counter reads below CUT_MAX_FT (5 ft). The turret index is not a cut: material
#     is still wound onto the old roll then. The first roll of a production session is the LEADER (roll 0); good rolls are 1, 2, ...
#     The length of a roll is the highest value its counter reached (the counter may be reset before the cut is seen).
#  3. Every SNAP_S seconds while producing it logs one snapshot of every logged process value (ROLL_LOG), keyed by where the fabric is:
#       W = cumulative feet wound,  stored = fabric between the coater and the winder = path_len_ft + acc_cap_ft * accumulator %,
#       G = W + stored = the winder-footage index of the fabric that is at the coater right now.
#     A roll wound over [w_start, w_end] was therefore processed when G was in that range, not when it was wound.
#  4. When a roll closes it stores per-tag statistics (ROLL_STAT) over the snapshots whose G falls inside the roll.
# State lives in Oracle (ROLL_STATE), so a gateway restart resumes the open roll (flagged GAP). Settings: table ROLL_CFG.
import sys

DB = 'myOracle'
P = '[cal1615]'
T_A_FT, T_B_FT = P + 'p29r13_ai_wa_footage_ft', P + 'p29r13_ai_wb_footage_ft'
# a winder is winding when its request-run bit is set: speed control (r10 / r11) or torque control (r15 / r16)
T_A_RUN, T_A_RUN2, T_B_RUN, T_B_RUN2 = P + 'p29r10_request_run', P + 'p29r15_request_run', P + 'p29r11_request_run', P + 'p29r16_request_run'
T_LINE, T_TANK, T_RTO = P + 'p01r13_line_running', P + 'p23_di_impreg_tank_up', P + 'p01r13_permissive_oxidizer'
T_ACC, T_SPEED = P + 'p00_wac_position_pct', P + 'p01r12_master_ramped_speed'
T_RECIPE, T_SHOP = P + 'p01_recipe_active/name/name', P + 'HMI/shop_order'
H = P + 'HMI/Rolls/'          # state shown on the page, and the operator buttons (pulses)
TAGS = []   # @@TAGS@@
DEFAULTS = [('path_len_ft', 0.0), ('acc_cap_ft', 0.0), ('snap_s', 10.0), ('cut_max_ft', 5.0), ('min_roll_ft', 100.0),
	('prod_off_s', 60.0), ('keep_days', 90.0), ('cfg_reload_s', 60.0), ('gates_needed', 1.0)]

GL = system.util.getGlobals()
log = system.util.getLogger('cal1615.rolls')
st = GL.get('cal1615_rolls')
if st is None:
	st = {'busy': False, 'ready': False, 'cfg': dict(DEFAULTS), 't_cfg': 0, 't_snap': 0, 't_clean': 0, 'mode': 'idle', 'roll': None, 'session': None,
		'wound': 0.0, 'prev_ft': {'A': None, 'B': None}, 'stopped_seen': False, 'manual': False, 'hold': False, 'off_since': None,
		'shown': {}, 'warned': {}, 'tagset': 0, 'pending': [], 't_retry': 0, 'last_inc': 0.0, 'rolls_done': 0, 'ft_done': 0.0, 'session_ms': None}
	GL['cal1615_rolls'] = st
for _k, _v in DEFAULTS:      # state kept in the globals by an older version of this script lacks settings added later
	st['cfg'].setdefault(_k, _v)


# ---------------------------------------------------------------- database
def ddl(sql, code):
	return "BEGIN EXECUTE IMMEDIATE '" + sql.replace("'", "''") + "'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != " + str(code) + " THEN RAISE; END IF; END;"

SCHEMA = [
	ddl("""CREATE TABLE ROLL (id NUMBER PRIMARY KEY, session_id NUMBER, roll_no NUMBER, leader NUMBER(1), winder VARCHAR2(1), status VARCHAR2(12),
		reason VARCHAR2(80), start_ts TIMESTAMP DEFAULT SYSTIMESTAMP, end_ts TIMESTAMP, start_ft NUMBER, end_ft NUMBER, length_ft NUMBER,
		w_start NUMBER, w_end NUMBER, path_len_ft NUMBER, acc_cap_ft NUMBER, recipe VARCHAR2(200), shop_order VARCHAR2(200), flags VARCHAR2(400),
		rows_n NUMBER, covered_ft NUMBER)""", -955),
	ddl("""CREATE TABLE ROLL_LOG (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id NUMBER, ts TIMESTAMP DEFAULT SYSTIMESTAMP,
		w_ft NUMBER, g_ft NUMBER, roll_no NUMBER, tagset NUMBER, vals CLOB)""", -955),
	ddl('CREATE INDEX ROLL_LOG_G ON ROLL_LOG (session_id, g_ft)', -955),
	ddl('CREATE TABLE ROLL_STAT (roll_id NUMBER, tag VARCHAR2(200), n NUMBER, avg_v NUMBER, min_v NUMBER, max_v NUMBER, sd_v NUMBER)', -955),
	ddl('CREATE INDEX ROLL_STAT_R ON ROLL_STAT (roll_id)', -955),
	ddl("""CREATE TABLE ROLL_EVENT (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts TIMESTAMP DEFAULT SYSTIMESTAMP, session_id NUMBER,
		roll_no NUMBER, kind VARCHAR2(20), message VARCHAR2(400))""", -955),
	ddl('CREATE TABLE ROLL_STATE (id NUMBER PRIMARY KEY, data CLOB, saved TIMESTAMP DEFAULT SYSTIMESTAMP)', -955),
	ddl('CREATE TABLE ROLL_CFG (k VARCHAR2(40) PRIMARY KEY, v NUMBER)', -955),
	ddl('CREATE TABLE ROLL_TAGSET (id NUMBER PRIMARY KEY, tags CLOB)', -955),
	ddl('CREATE SEQUENCE ROLL_SEQ', -955),
]


def err(key, msg):
	"""Log an error at most once a minute per kind: a database outage must not write two lines every half second."""
	now = system.date.now().getTime()
	if now - st['warned'].get(key, 0) >= 60000:
		st['warned'][key] = now
		log.error(msg)


def clob_text(v):
	if v is None:
		return None
	if isinstance(v, basestring):
		return v
	if hasattr(v, 'getSubString'):
		return v.getSubString(1, int(v.length()))
	return str(v)


def ensure_db():
	if st['ready']:
		return
	for sql in SCHEMA:
		system.db.runUpdateQuery(sql, DB)
	for k, v in DEFAULTS:
		system.db.runPrepUpdate('MERGE INTO ROLL_CFG c USING (SELECT ? AS k, ? AS v FROM DUAL) s ON (c.k = s.k) WHEN NOT MATCHED THEN INSERT (k, v) VALUES (s.k, s.v)', [k, v], DB)
	n = system.db.runScalarPrepQuery('SELECT COUNT(*) FROM ROLL_TAGSET WHERE id = ?', [st['tagset']], DB)
	if not n:
		system.db.runPrepUpdate('INSERT INTO ROLL_TAGSET (id, tags) VALUES (?, ?)', [st['tagset'], system.util.jsonEncode(TAGS)], DB)
	st['ready'] = True


def load_cfg(now):
	if now - st['t_cfg'] < st['cfg']['cfg_reload_s'] * 1000.0 and st['t_cfg']:
		return
	st['t_cfg'] = now
	try:
		for r in system.db.runPrepQuery('SELECT k AS "k", v AS "v" FROM ROLL_CFG', [], DB):
			if r['v'] is not None:
				st['cfg'][r['k']] = float(r['v'])
	except:
		err('cfg', 'Could not read ROLL_CFG: %s' % sys.exc_info()[1])


def event(kind, msg, roll=None):
	r = roll or st['roll']
	log.info('%s: %s' % (kind, msg))
	st['msg'] = msg
	try:
		system.db.runPrepUpdate('INSERT INTO ROLL_EVENT (session_id, roll_no, kind, message) VALUES (?, ?, ?, ?)',
			[st['session'], None if r is None else r['no'], kind, msg[:400]], DB)
	except:
		err('event', 'Could not write ROLL_EVENT: %s' % sys.exc_info()[1])


def save_state():
	try:
		data = system.util.jsonEncode({'mode': st['mode'], 'roll': st['roll'], 'session': st['session'], 'wound': st['wound'],
			'manual': st['manual'], 'hold': st['hold'], 'rolls_done': st['rolls_done'], 'ft_done': st['ft_done'], 'session_ms': st['session_ms']})
		system.db.runPrepUpdate('MERGE INTO ROLL_STATE s USING (SELECT 1 AS id FROM DUAL) d ON (s.id = d.id) WHEN MATCHED THEN UPDATE SET data = ?, saved = SYSTIMESTAMP WHEN NOT MATCHED THEN INSERT (id, data) VALUES (1, ?)',
			[data, data], DB)
	except:
		err('state', 'Could not save the roll state: %s' % sys.exc_info()[1])


def save_roll(roll):
	"""Insert (first time) or update the ROLL row; True when it worked. A failure leaves roll['id'] unset so the next save inserts the whole row;
	a closed roll that could not be saved is retried from st['pending'] (see retry_pending)."""
	cfg = st['cfg']
	try:
		if roll.get('id') is None:
			roll['id'] = int(system.db.runScalarPrepQuery('SELECT ROLL_SEQ.NEXTVAL FROM DUAL', [], DB))
			system.db.runPrepUpdate('INSERT INTO ROLL (id, session_id, roll_no, leader, winder, status, start_ft, w_start, path_len_ft, acc_cap_ft, recipe, shop_order, flags) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
				[roll['id'], roll['session'], roll['no'], 1 if roll['leader'] else 0, roll['winder'], 'OPEN', roll['start_ft'], roll['w_start'],
				cfg['path_len_ft'], cfg['acc_cap_ft'], roll.get('recipe'), roll.get('shop'), ','.join(roll['flags'])], DB)
		if roll['status'] != 'OPEN':
			system.db.runPrepUpdate('UPDATE ROLL SET status = ?, reason = ?, end_ts = SYSTIMESTAMP, end_ft = ?, length_ft = ?, w_end = ?, flags = ?, rows_n = ?, covered_ft = ?, winder = ? WHERE id = ?',
				[roll['status'], roll['reason'][:80], roll['end_ft'], roll['length_ft'], roll['w_end'], ','.join(roll['flags'])[:400], roll.get('rows_n'), roll.get('covered_ft'), roll['winder'], roll['id']], DB)
		else:
			system.db.runPrepUpdate('UPDATE ROLL SET flags = ? WHERE id = ?', [','.join(roll['flags'])[:400], roll['id']], DB)
		return True
	except:
		err('roll', 'Could not save roll %s: %s' % (roll.get('no'), sys.exc_info()[1]))
		if roll['status'] != 'OPEN' and roll not in st['pending']:
			st['pending'].append(roll)
		return False


def roll_stats(roll):
	"""Per-tag statistics over the snapshots whose G (fabric position at the coater) lies inside the roll."""
	n_tags = len(TAGS)
	cnt, tot, sq = [0] * n_tags, [0.0] * n_tags, [0.0] * n_tags
	mn, mx = [None] * n_tags, [None] * n_tags
	rows, gmin, gmax = 0, None, None
	ds = system.db.runPrepQuery('SELECT g_ft AS "g", vals AS "vals" FROM ROLL_LOG WHERE session_id = ? AND tagset = ? AND g_ft >= ? AND g_ft <= ? ORDER BY g_ft',
		[roll['session'], st['tagset'], roll['w_start'], roll['w_end']], DB)
	for r in ds:
		vals = system.util.jsonDecode(clob_text(r['vals']))
		rows += 1
		g = float(r['g'])
		gmin = g if gmin is None else min(gmin, g)
		gmax = g if gmax is None else max(gmax, g)
		for i in range(min(n_tags, len(vals))):
			v = vals[i]
			if v is None:
				continue
			cnt[i] += 1
			tot[i] += v
			sq[i] += v * v
			mn[i] = v if mn[i] is None else min(mn[i], v)
			mx[i] = v if mx[i] is None else max(mx[i], v)
	roll['rows_n'] = rows
	roll['covered_ft'] = 0.0 if rows == 0 else gmax - gmin
	out = []
	for i in range(n_tags):
		if cnt[i]:
			avg = tot[i] / cnt[i]
			out.append([roll['id'], TAGS[i], cnt[i], avg, mn[i], mx[i], max(sq[i] / cnt[i] - avg * avg, 0.0) ** 0.5])
	for k in range(0, len(out), 40):
		chunk = out[k:k + 40]
		sql = 'INSERT ALL ' + ' '.join(['INTO ROLL_STAT (roll_id, tag, n, avg_v, min_v, max_v, sd_v) VALUES (?, ?, ?, ?, ?, ?, ?)'] * len(chunk)) + ' SELECT 1 FROM DUAL'
		args = []
		for row in chunk:
			args.extend(row)
		system.db.runPrepUpdate(sql, args, DB)


def retry_pending(now):
	"""Closed rolls whose save failed (database down): try again every 10 s, statistics first when they were skipped."""
	if not st['pending'] or now - st['t_retry'] < 10000:
		return
	st['t_retry'] = now
	for roll in list(st['pending']):
		if 'NOSTATS' in roll['flags']:
			try:
				roll_stats(roll)
				roll['flags'].remove('NOSTATS')
			except:
				continue
		if save_roll(roll):
			if roll in st['pending']:
				st['pending'].remove(roll)


# ---------------------------------------------------------------- the state machine
def new_roll(no, leader, winder, ft, reason):
	cfg = st['cfg']
	start_ft = ft if leader else 0.0       # a cut roll starts at 0: the counter was just reset (it reads < CUT_MAX_FT)
	roll = {'id': None, 'session': st['session'], 'no': no, 'leader': leader, 'winder': winder, 'start_ft': start_ft, 'max_ft': ft,
		'w_start': st['wound'] - (ft - start_ft), 'status': 'OPEN', 'reason': '', 'flags': [], 'recipe': st.get('recipe'), 'shop': st.get('shop')}
	if cfg['path_len_ft'] <= 0.0:
		roll['flags'].append('NOPATH')       # the stored-fabric offset is not configured: statistics are not shifted to the coater
	st['roll'] = roll
	st['stopped_seen'] = False
	save_roll(roll)
	event('LEADER' if leader else 'ROLL', '%s roll %d started on winder %s (%s), counter %.1f ft' % ('Leader' if leader else 'Good', no, winder, reason, ft), roll)
	save_state()


def close_roll(status, reason):
	roll = st['roll']
	if roll is None:
		return
	roll['status'], roll['reason'] = status, reason
	roll['end_ft'] = roll['max_ft']
	roll['length_ft'] = max(0.0, roll['max_ft'] - roll['start_ft'])
	roll['w_end'] = roll['w_start'] + roll['length_ft']
	if not roll['leader']:                 # the job counters on the Overview: good feet, and good rolls that were cut (not a partial at the end)
		st['ft_done'] += roll['length_ft']
		if status == 'CLOSED':
			st['rolls_done'] += 1
	try:
		roll_stats(roll)
	except:
		log.error('Statistics for roll %d failed: %s' % (roll['no'], sys.exc_info()[1]))
		roll['flags'].append('NOSTATS')
	if roll['length_ft'] < st['cfg']['min_roll_ft'] and not roll['leader']:
		roll['flags'].append('SHORT')
	save_roll(roll)
	event('CLOSE', 'Roll %d closed (%s): %.0f ft on winder %s, %d snapshots%s' % (roll['no'], reason, roll['length_ft'], roll['winder'], roll.get('rows_n') or 0,
		(', flags ' + ','.join(roll['flags'])) if roll['flags'] else ''), roll)
	st['roll'] = None


def flag(roll, name, msg):
	"""Record a flag on the open roll once."""
	if name not in roll['flags']:
		roll['flags'].append(name)
		event('WARN', msg, roll)
		save_roll(roll)


def read_inputs():
	paths = [T_A_FT, T_B_FT, T_A_RUN, T_A_RUN2, T_B_RUN, T_B_RUN2, T_LINE, T_TANK, T_RTO, T_ACC, T_SPEED, T_RECIPE, T_SHOP, H + 'prod_start', H + 'prod_stop']
	v = {}
	for p, r in zip(paths, system.tag.readBlocking(paths)):
		v[p] = r.value if r.quality.isGood() else None
	if None in (v[T_A_FT], v[T_B_FT], v[T_A_RUN], v[T_B_RUN], v[T_LINE]):
		return None                          # the essential tags are bad: change nothing this tick
	return {'ft': {'A': float(v[T_A_FT]), 'B': float(v[T_B_FT])},
		'a_run': bool(v[T_A_RUN] or v[T_A_RUN2]), 'b_run': bool(v[T_B_RUN] or v[T_B_RUN2]), 'line': bool(v[T_LINE]),
		'gates': bool(v[T_TANK]) and bool(v[T_RTO]), 'acc': v[T_ACC], 'speed': v[T_SPEED], 'recipe': v[T_RECIPE], 'shop': v[T_SHOP],
		'start': bool(v[H + 'prod_start']), 'stop': bool(v[H + 'prod_stop'])}


def snapshot(inp, now):
	cfg = st['cfg']
	if st['mode'] != 'prod' or not inp['line'] or now - st['t_snap'] < cfg['snap_s'] * 1000.0:
		return
	st['t_snap'] = now
	vals = []
	for r in system.tag.readBlocking(TAGS):
		v = r.value if r.quality.isGood() else None
		vals.append(float(v) if isinstance(v, (int, long, float)) and not isinstance(v, bool) else None)
	acc = inp['acc'] if inp['acc'] is not None else 0.0
	stored = cfg['path_len_ft'] + cfg['acc_cap_ft'] * acc / 100.0
	try:
		system.db.runPrepUpdate('INSERT INTO ROLL_LOG (session_id, w_ft, g_ft, roll_no, tagset, vals) VALUES (?, ?, ?, ?, ?, ?)',
			[st['session'], st['wound'], st['wound'] + stored, st['roll']['no'] if st['roll'] else None, st['tagset'], system.util.jsonEncode(vals)], DB)
	except:
		err('snap', 'Could not write a roll snapshot: %s' % sys.exc_info()[1])
	save_state()


def publish(inp):
	roll = st['roll']
	want = {'state': {'idle': 'IDLE', 'prod': 'PRODUCING'}[st['mode']] if not (roll and roll['leader']) else 'LEADER',
		'roll_no': -1 if roll is None else roll['no'], 'roll_ft': 0.0 if roll is None else round(max(0.0, roll['max_ft'] - roll['start_ft']), 1),
		'winder': '' if roll is None else roll['winder'], 'msg': st.get('msg', ''),
		'rolls_done': st['rolls_done'], 'ft_done': round(st['ft_done'] + (0.0 if (roll is None or roll['leader']) else max(0.0, roll['max_ft'] - roll['start_ft'])), 0)}
	if st['session_ms'] is not None:
		want['session_start'] = system.date.fromMillis(st['session_ms'])
	chg = [k for k in want if st['shown'].get(k) != want[k]]
	if chg:
		try:
			system.tag.writeBlocking([H + k for k in chg], [want[k] for k in chg])
			for k in chg:
				st['shown'][k] = want[k]
		except:
			log.warn('Could not publish roll state: %s' % sys.exc_info()[1])


def step(inp, now):
	cfg = st['cfg']
	a, b = inp['a_run'], inp['b_run']
	w = 'A' if (a and not b) else ('B' if (b and not a) else None)
	if inp['recipe'] is not None:
		st['recipe'] = inp['recipe']
	if inp['shop'] is not None:
		st['shop'] = inp['shop']
	# cumulative feet wound: only the winder that is winding adds, and a counter reset (a drop) adds nothing
	st['last_inc'] = 0.0
	for x in ('A', 'B'):
		ft, prev = inp['ft'][x], st['prev_ft'][x]
		if prev is not None and w == x and 0.0 < ft - prev < 500.0:
			st['wound'] += ft - prev
			st['last_inc'] = ft - prev
		st['prev_ft'][x] = ft
	roll = st['roll']
	if roll is not None and w == roll['winder']:
		roll['max_ft'] = max(roll['max_ft'], inp['ft'][w])
	# operator buttons (pulses)
	if inp['start']:
		st['manual'], st['hold'] = True, False
		event('MANUAL', 'Production start pressed')
	if inp['stop']:
		st['manual'], st['hold'] = False, True
		if st['mode'] == 'prod':
			close_roll('PARTIAL', 'production stopped by the operator')
			st['mode'] = 'idle'
			save_state()
		event('MANUAL', 'Production stop pressed')
	if inp['start'] or inp['stop']:
		try:
			system.tag.writeBlocking([H + 'prod_start', H + 'prod_stop'], [False, False])
		except:
			pass
	gated = cfg['gates_needed'] >= 0.5      # 0 = count rolls whenever the line runs (for a plant or simulator where the tank / RTO bits are not available)
	want = inp['gates'] or st['manual'] or not gated
	if (gated and not inp['gates']) or (not gated and not inp['line']):
		st['hold'] = False                   # the gates dropped (or, without gates, the line stopped): allow the next production start
	if st['mode'] == 'idle':
		if want and not st['hold'] and inp['line'] and w is not None:
			st['mode'], st['session'], st['wound'], st['off_since'] = 'prod', int(system.db.runScalarPrepQuery('SELECT ROLL_SEQ.NEXTVAL FROM DUAL', [], DB)), st['last_inc'], None
			st['t_snap'] = 0
			st['rolls_done'], st['ft_done'], st['session_ms'] = 0, 0.0, now
			event('START', 'Production started (tank up, RTO ready%s); winder %s is winding' % (', operator override' if st['manual'] and not inp['gates'] else '', w))
			new_roll(0, True, w, inp['ft'][w], 'production start')
		return
	# ---- producing
	if want:
		st['off_since'] = None
	else:
		if st['off_since'] is None:
			st['off_since'] = now
		if now - st['off_since'] >= cfg['prod_off_s'] * 1000.0:
			close_roll('PARTIAL', 'tank down or RTO not ready')
			st['mode'] = 'idle'
			event('END', 'Production ended: tank down or RTO not ready for %d s' % cfg['prod_off_s'])
			save_state()
			return
	roll = st['roll']
	if roll is None:                         # should not happen; start a fresh roll on the next winding winder
		if w is not None:
			st['roll_no'] = st.get('roll_no', 0) + 1
			new_roll(st['roll_no'], False, w, inp['ft'][w], 'no open roll')
		return
	st['roll_no'] = roll['no']
	if w == roll['winder']:
		st['stopped_seen'] = False
		if inp['ft'][w] < cfg['cut_max_ft'] and roll['max_ft'] - roll['start_ft'] >= cfg['min_roll_ft']:
			# the same winder starts again with its counter reset: a new roll on the same winder
			close_roll('CLOSED', 'counter reset on winder %s' % w)
			new_roll(st['roll_no'] + 1, False, w, inp['ft'][w], 'counter reset')
	elif w is None:
		if not a and not b:
			st['stopped_seen'] = True        # both winders stopped: the window in which a cut can happen
	else:
		# the other winder is winding
		if st['stopped_seen'] and inp['ft'][w] < cfg['cut_max_ft']:
			close_roll('CLOSED', 'cutover to winder %s' % w)
			new_roll(st['roll_no'] + 1, False, w, inp['ft'][w], 'cutover from winder %s' % ('B' if w == 'A' else 'A'))
		elif inp['ft'][w] >= cfg['cut_max_ft']:
			flag(roll, 'NOCLEAR', 'Winder %s is winding but its counter reads %.0f ft (not below %.0f): the cut was not counted. Reset the counter.' % (w, inp['ft'][w], cfg['cut_max_ft']))


def run():
	now = system.date.now().getTime()
	if not st['ready']:
		h = 7
		for p in TAGS:
			for ch in p:
				h = (h * 31 + ord(ch)) % 2147483647
		st['tagset'] = h
		ensure_db()
		restore()
	load_cfg(now)
	inp = read_inputs()
	if inp is None:
		return
	retry_pending(now)
	step(inp, now)
	snapshot(inp, now)
	publish(inp)
	if now - st['t_clean'] > 3600000:
		st['t_clean'] = now
		try:
			system.db.runPrepUpdate("DELETE FROM ROLL_LOG WHERE ts < SYSTIMESTAMP - NUMTODSINTERVAL(?, 'DAY')", [st['cfg']['keep_days']], DB)
		except:
			log.warn('Roll log cleanup failed: %s' % sys.exc_info()[1])


def restore():
	"""After a gateway restart: pick the open roll up again. Feet wound while the gateway was down are unknown, so the roll is flagged GAP."""
	try:
		txt = clob_text(system.db.runScalarPrepQuery('SELECT data FROM ROLL_STATE WHERE id = 1', [], DB))
	except:
		txt = None
	if not txt:
		return
	d = system.util.jsonDecode(txt)
	if d.get('mode') == 'prod' and d.get('roll'):
		st['mode'], st['roll'], st['session'], st['wound'] = 'prod', d['roll'], d['session'], float(d['wound'])
		st['manual'], st['hold'] = bool(d.get('manual')), bool(d.get('hold'))
		st['rolls_done'], st['ft_done'], st['session_ms'] = int(d.get('rolls_done') or 0), float(d.get('ft_done') or 0.0), d.get('session_ms')
		st['roll_no'] = d['roll']['no']
		flag(st['roll'], 'GAP', 'Roll logging resumed after a restart: roll %d was open; feet wound while it was down are not counted.' % d['roll']['no'])


if not st['busy']:                           # two overlapping runs would double-count
	st['busy'] = True
	try:
		run()
	except:
		log.error('Roll logging failed: %s' % sys.exc_info()[1])
	finally:
		st['busy'] = False
