IF OBJECT_ID(N'dbo.rcp_cal1615', N'U') IS NULL
CREATE TABLE dbo.rcp_cal1615 (
	id INT IDENTITY(1,1) PRIMARY KEY,
	name NVARCHAR(100) NOT NULL UNIQUE,
	comments NVARCHAR(255) NULL,
	[zone_1__recirc_sp] FLOAT NULL,
	[zone_1__exhaust_sp] FLOAT NULL,
	[zone_1__temp_sp] FLOAT NULL,
	[zone_2__recirc_sp] FLOAT NULL,
	[zone_2__exhaust_sp] FLOAT NULL,
	[zone_2__temp_sp] FLOAT NULL,
	[zone_3__recirc_sp] FLOAT NULL,
	[zone_3__exhaust_sp] FLOAT NULL,
	[zone_3__temp_sp] FLOAT NULL,
	[line_speed_sp] FLOAT NULL,
	[letoff_tension_sp] FLOAT NULL,
	[acc_tension_sp] FLOAT NULL,
	[acc_fill_pressure_sp] FLOAT NULL,
	[acc_counter_pressure_sp] FLOAT NULL,
	[cure_time_sp] FLOAT NULL,
	[platen_temp_sp] FLOAT NULL,
	[impreg_gap_sp] FLOAT NULL,
	[impreg_gap_ds_offset_sp] FLOAT NULL,
	[impreg_gap_os_offset_sp] FLOAT NULL,
	[impreg_supply_speed_sp] FLOAT NULL,
	[ts1_mode_sp] FLOAT NULL,
	[ts1_tension_sp] FLOAT NULL,
	[ts1_stretch_sp] FLOAT NULL,
	[slitter_speed_sp] FLOAT NULL,
	[adv_cooling_temp_sp] FLOAT NULL,
	[ts2_tension_sp] FLOAT NULL,
	[lower_poly_tension_sp] FLOAT NULL,
	[lower_poly_b_tension_sp] FLOAT NULL,
	[upper_poly_tension_sp] FLOAT NULL,
	[upper_poly_b_tension_sp] FLOAT NULL,
	[winder_tension_sp] FLOAT NULL,
	[winder_mode_sp] FLOAT NULL,
	[winder_torque_sp] FLOAT NULL,
	[tension_deviation_sp] FLOAT NULL,
	modified DATETIME NOT NULL DEFAULT GETDATE()
)