# cal1615 PID tuning runner. Two kinds of test, on the loops defined in cal1615.pid.LOOPS (each has a 'test' section):
#
#   steady   SP bumps at steady state (oven zones and the tension loops). ACTIVE: it writes the SP through the HMI input
#            (the same tag a recipe download writes) and restores it. Result: gains for the loop's normal control gain set.
#   heatup   Cold-start capture (oven zones only). PASSIVE: it never writes anything. The operator starts the heat as usual;
#            the runner records PV / SP / CV from before the burner lights until the zone reaches SP, then analyses the climb
#            (Siemens-pretuning style: steepest rise + dead time, plus a model fit). Result: gains for the Fast PID
#            (zone 3 only has one set, so it gets the Auto PID).
#
# SAFETY of the active test (each of these ends it and restores the original SP):
#   operator Abort; the loop leaves its normal state; a fault; PV runs away; CV pinned at a limit; bad tag quality;
#   an SP write the PLC does not take; the test takes too long.
#   If someone else changes the SP while a test runs (for example a recipe download), the test stops and does NOT put the old
#   SP back over their change.
# The SP the test is about to command is stored in the database BEFORE it is written, together with a heartbeat. A gateway
# watchdog (tag HMI/tune_watchdog) and recover() put the SP back when a test's heartbeat stops (gateway restart, dead thread),
# unless the SP is no longer the value the test commanded.
from __future__ import division
import time
import sys

DB = 'myOracle'
_log = system.util.getLogger('cal1615.tunerun')

def _plsql_ignore(sql, code):
	return "BEGIN EXECUTE IMMEDIATE '%s'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> %d THEN RAISE; END IF; END;" % (sql.replace("'", "''"), code)

_CREATE = _plsql_ignore("""CREATE TABLE PID_TUNE_RUN (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	loop_id VARCHAR2(40), username VARCHAR2(100), status VARCHAR2(30), message VARCHAR2(500),
	orig_sp NUMBER, sp_tag VARCHAR2(200), bump NUMBER,
	started TIMESTAMP DEFAULT SYSTIMESTAMP, hb TIMESTAMP DEFAULT SYSTIMESTAMP, ended TIMESTAMP, data NCLOB)""", -955)
_CREATE_APPLY = _plsql_ignore("""CREATE TABLE PID_TUNE_APPLY (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	run_id NUMBER, loop_id VARCHAR2(40), username VARCHAR2(100), applied TIMESTAMP DEFAULT SYSTIMESTAMP,
	old_kp NUMBER, old_ki NUMBER, new_kp NUMBER, new_ki NUMBER, kp_tag VARCHAR2(200), ki_tag VARCHAR2(200),
	reverted TIMESTAMP, reverted_by VARCHAR2(100))""", -955)
# columns added later (ORA-01430 = the column already exists)
_MIGRATE = [
	_plsql_ignore('ALTER TABLE PID_TUNE_RUN ADD (run_mode VARCHAR2(20))', -1430),
	_plsql_ignore('ALTER TABLE PID_TUNE_RUN ADD (last_cmd NUMBER)', -1430),
	_plsql_ignore('ALTER TABLE PID_TUNE_APPLY ADD (gain_set VARCHAR2(10))', -1430),
]
HB_STALE_S = 60.0     # a RUNNING row whose heartbeat is older than this belongs to a dead test
HB_EVERY_S = 15.0

# zone status codes (cal1615.zones / PLC routine R20)
STATUS_NAMES = {1: 'Off', 2: 'Idle', 3: 'Start Recirc', 4: 'Start Exhaust', 5: 'Wait Safeties', 6: 'Safeties Made', 7: 'Purge', 8: 'Burner Lit',
	9: 'Heat to SP', 10: 'Control to SP', 11: 'Cooldown', 12: 'Cooldown Fans', 13: 'Complete', 31: 'Manual'}
HEATING = (3, 4, 5, 6, 7, 8, 9, 10)     # from "Start Recirc" through "Control to SP"
NOT_STARTED = (1, 2, 13)
MODE_NAMES = {'steady': 'SP bumps at steady state', 'heatup': 'Heat-up from cold'}

class AbortTest(Exception):
	"""Ends the test; whatever was captured is stored but not analysed."""
	pass

class ExternalChange(AbortTest):
	"""Someone else changed the SP while the test ran: stop and leave their value alone."""
	pass

class EndCapture(Exception):
	"""Heat-up capture finished (or was cut short): analyse what was captured."""
	pass

# ---------------------------------------------------------------- database (thin, so tests can replace them)
_tables_ok = [False]

def _db_ready():
	"""Create the tables when missing and add later columns; once per gateway run."""
	if _tables_ok[0]:
		return
	system.db.runUpdateQuery(_CREATE, DB)
	system.db.runUpdateQuery(_CREATE_APPLY, DB)
	for sql in _MIGRATE:
		system.db.runUpdateQuery(sql, DB)
	_tables_ok[0] = True

def _db_insert(loop_id, user, orig_sp, sp_tag, bump, mode):
	_db_ready()
	system.db.runPrepUpdate("INSERT INTO PID_TUNE_RUN (loop_id, username, status, orig_sp, last_cmd, sp_tag, bump, run_mode) VALUES (?, ?, 'RUNNING', ?, ?, ?, ?, ?)",
		[loop_id, user, orig_sp, orig_sp, sp_tag, bump, mode], DB)
	return int(system.db.runScalarPrepQuery("SELECT MAX(id) FROM PID_TUNE_RUN WHERE loop_id = ? AND username = ? AND status = 'RUNNING'", [loop_id, user], DB))

def _db_finish(run_id, status, message, data):
	system.db.runPrepUpdate('UPDATE PID_TUNE_RUN SET status = ?, message = ?, data = ?, ended = SYSTIMESTAMP WHERE id = ?',
		[status, (message or '')[:480], system.util.jsonEncode(data) if data is not None else None, run_id], DB)

def _db_heartbeat(run_id, last_cmd=None):
	"""Heartbeat; when the test is about to command a new SP, call this FIRST with that value (so a crash between the two steps
	still leaves the database matching or behind the PLC, never ahead of it)."""
	if last_cmd is None:
		system.db.runPrepUpdate('UPDATE PID_TUNE_RUN SET hb = SYSTIMESTAMP WHERE id = ?', [run_id], DB)
	else:
		system.db.runPrepUpdate('UPDATE PID_TUNE_RUN SET hb = SYSTIMESTAMP, last_cmd = ? WHERE id = ?', [last_cmd, run_id], DB)

def _db_running():
	"""Tests that are still marked RUNNING, with the age (s) of their last heartbeat."""
	_db_ready()
	ds = system.db.runPrepQuery("SELECT id AS \"id\", loop_id AS \"loop_id\", run_mode AS \"mode\", orig_sp AS \"orig_sp\", last_cmd AS \"last_cmd\", sp_tag AS \"sp_tag\", (CAST(SYSTIMESTAMP AS DATE) - CAST(hb AS DATE)) * 86400 AS \"age\" FROM PID_TUNE_RUN WHERE status = 'RUNNING'", [], DB)
	out = []
	for r in ds:
		out.append({'id': int(r['id']), 'loop_id': r['loop_id'], 'mode': r['mode'] or 'steady', 'sp_tag': r['sp_tag'],
			'orig_sp': None if r['orig_sp'] is None else float(r['orig_sp']), 'last_cmd': None if r['last_cmd'] is None else float(r['last_cmd']),
			'age': float(r['age'] or 0.0)})
	return out

def _db_last(loop_id):
	_db_ready()
	ds = system.db.runPrepQuery("SELECT id AS \"id\", status AS \"status\", message AS \"message\", data AS \"data\" FROM PID_TUNE_RUN WHERE loop_id = ? AND status IN ('DONE', 'ABORTED', 'ERROR', 'RECOVERED') ORDER BY id DESC FETCH FIRST 1 ROWS ONLY", [loop_id], DB)
	if ds.getRowCount() == 0:
		return None
	d = ds[0]['data']
	if d is not None and not isinstance(d, basestring) and hasattr(d, 'getSubString'):
		d = d.getSubString(1, int(d.length()))
	return {'id': int(ds[0]['id']), 'status': ds[0]['status'], 'message': ds[0]['message'], 'data': system.util.jsonDecode(d) if d else None}

def _db_last_apply(loop_id):
	_db_ready()
	ds = system.db.runPrepQuery('SELECT id AS "id", run_id AS "run_id", username AS "username", gain_set AS "gain_set", old_kp AS "old_kp", old_ki AS "old_ki", new_kp AS "new_kp", new_ki AS "new_ki" FROM PID_TUNE_APPLY WHERE loop_id = ? AND reverted IS NULL ORDER BY id DESC FETCH FIRST 1 ROWS ONLY', [loop_id], DB)
	if ds.getRowCount() == 0:
		return None
	r = ds[0]
	return {'id': int(r['id']), 'run_id': int(r['run_id']), 'user': r['username'], 'gain_set': r['gain_set'] or 'pid2', 'old_kp': float(r['old_kp']), 'old_ki': float(r['old_ki']),
		'new_kp': float(r['new_kp']), 'new_ki': float(r['new_ki'])}

def _db_insert_apply(run_id, loop_id, user, gain_set, old_kp, old_ki, new_kp, new_ki):
	system.db.runPrepUpdate('INSERT INTO PID_TUNE_APPLY (run_id, loop_id, username, gain_set, old_kp, old_ki, new_kp, new_ki) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
		[run_id, loop_id, user, gain_set, old_kp, old_ki, new_kp, new_ki], DB)

def _db_mark_reverted(apply_id, user):
	system.db.runPrepUpdate('UPDATE PID_TUNE_APPLY SET reverted = SYSTIMESTAMP, reverted_by = ? WHERE id = ?', [user, apply_id], DB)

# ---------------------------------------------------------------- state shared with the page (survives script reloads)
def _state():
	g = system.util.getGlobals()
	if 'cal1615_tunerun' not in g:
		g['cal1615_tunerun'] = {'running': False, 'abort': False, 'finish': False, 'phase': 'idle', 'message': '', 'heartbeat': 0.0, 'events': []}
	return g['cal1615_tunerun']

def _event(s, text):
	s['events'] = (list(s.get('events', [])) + ['%s  %s' % (system.date.format(system.date.now(), 'HH:mm:ss'), text)])[-40:]
	_log.info(text)

def _median(v):
	s = sorted(v)
	n = len(s)
	if n == 0:
		return None
	return s[n // 2] if n % 2 else 0.5 * (s[n // 2 - 1] + s[n // 2])

# ---------------------------------------------------------------- loop configuration (the registry is cal1615.pid.LOOPS)
def _reg(loop_id):
	return cal1615.pid.LOOPS.get(loop_id)

def supported(loop_id):
	r = _reg(loop_id)
	return bool(r and r.get('test'))

def modes_for(loop_id):
	return list(_reg(loop_id)['test']['modes']) if supported(loop_id) else []

def gain_set_for(loop_id, mode):
	"""'pid1' = Fast PID, 'pid2' = Auto PID (the only set on zone 3 and on the tension loops)."""
	t = _reg(loop_id)['test']
	return t.get('heat_set', 'pid2') if mode == 'heatup' else 'pid2'

def set_label(loop_id, gain_set):
	r = _reg(loop_id)
	return r.get('set1' if gain_set == 'pid1' else 'set2') or ('Fast PID' if gain_set == 'pid1' else 'Gains')

def loop_config(loop_id, mode='steady'):
	"""Everything the runner needs for one loop and mode: the registry's test section plus the gain tags of the set being tuned."""
	r = _reg(loop_id)
	cfg = dict(r['test'])
	g = r['gains']
	gs = gain_set_for(loop_id, mode)
	if mode == 'heatup':
		cfg['max_total_s'] = cfg['arm_timeout_s'] + cfg['max_heat_s'] + 600.0
	for i, pair in enumerate(cfg.get('must_be_off', [])):
		cfg['off%d' % i], cfg['off%d_text' % i] = pair[0], pair[1]
	cfg.update({'id': loop_id, 'mode': mode, 'units': r.get('units', ''), 'label': r.get('label', loop_id), 'gain_set': gs,
		'kp': g[gs + '_kp'], 'ki': g[gs + '_ki'], 'kd': g[gs + '_kd'], 'kp_w': g[gs + '_kp_w'], 'ki_w': g[gs + '_ki_w']})
	return cfg

def _read(paths):
	rs = system.tag.readBlocking(paths)
	return [(r.value, r.quality.isGood()) for r in rs]

def _read_ts(paths):
	"""(value, good, timestamp in ms) for each path."""
	rs = system.tag.readBlocking(paths)
	out = []
	for r in rs:
		ts = None
		try:
			ts = r.timestamp.getTime()
		except Exception:
			pass
		out.append((r.value, r.quality.isGood(), ts))
	return out

# ---------------------------------------------------------------- readiness checklist and pre-check (one source for both)
def _off_keys(cfg):
	return [k for k in sorted(cfg) if k.startswith('off') and k[3:].isdigit()]

def _keys_for(cfg, mode):
	if cfg['kind'] == 'temperature':
		return ['pv', 'sp', 'sp_w', 'cv', 'status', 'faults_ok', 'auto', 'hl', 'dev', 'soak_to_fast', 'kp', 'ki', 'kd']
	return ['pv', 'sp', 'sp_w', 'cv', 'active', 'line_running', 'swm', 'kp', 'ki', 'kd'] + _off_keys(cfg)

def _status_text(code):
	try:
		return '%s (%d)' % (STATUS_NAMES.get(int(code), '?'), int(code))
	except Exception:
		return str(code)

def _checks(cfg, mode, bump, busy):
	"""List of {'ok': True / False / None (operator confirms), 'text': what is checked, 'fail': why a start is refused}, and the values read."""
	items = []
	def add(ok, text, fail=None):
		items.append({'ok': ok, 'text': text, 'fail': fail or text})
	keys = _keys_for(cfg, mode)
	vals = _read([cfg[k] for k in keys])
	v = {}
	unreadable = []
	for k, (val, good) in zip(keys, vals):
		v[k] = val
		if (not good) or val is None:
			unreadable.append(k)
	add(not busy, 'No other tuning test is running', 'A tuning test is already running.')
	if unreadable:
		add(False, 'All tags can be read', 'These tags cannot be read: %s.' % ', '.join(unreadable))
		return items, v
	add(True, 'All tags can be read')
	u = cfg['units']
	if cfg['kind'] == 'temperature' and mode == 'heatup':
		add(None, 'Oven is empty, doors closed, nothing else is changing', None)
		cold = v['sp'] - v['pv']
		add(cold >= cfg['cold_margin'], 'Oven is cold: PV %.0f, SP %.0f (PV must be %.0f %s or more below SP)' % (v['pv'], v['sp'], cfg['cold_margin'], u),
			'The oven is not cold: PV is %.1f and SP is %.1f; PV must be at least %.0f %s below SP.' % (v['pv'], v['sp'], cfg['cold_margin'], u))
		add(int(v['status']) in NOT_STARTED, 'Zone has not started heating: %s' % _status_text(v['status']),
			'The zone must not be heating yet (status %s now). Arm the capture first, then start the heat.' % _status_text(v['status']))
		add(bool(v['faults_ok']), 'No fault on the zone', 'The zone reports a fault.')
		add(bool(v['auto']), 'Valve is in auto', 'The control valve is in manual.')
		add(None, 'After arming: press Start Heat on the zone page. The capture waits up to %d minutes for the burner.' % int(cfg['arm_timeout_s'] / 60), None)
		return items, v
	if cfg['kind'] == 'temperature':
		add(None, 'Oven is empty, doors closed, nothing else is changing', None)
		add(abs(v['sp'] - v['sp_w']) <= 0.05, 'SP has settled (active %.1f, commanded %.1f)' % (v['sp'], v['sp_w']),
			'The zone SP is still changing (active %.1f, commanded %.1f). Wait a few seconds and try again.' % (v['sp'], v['sp_w']))
		add(int(v['status']) == cfg['status_ok'], 'Zone is in Control to SP: %s' % _status_text(v['status']),
			'The zone must be in "Control to SP" (status %s now).' % _status_text(v['status']))
		add(bool(v['faults_ok']), 'No fault on the zone', 'The zone reports a fault.')
		add(bool(v['auto']), 'Valve is in auto', 'The control valve is in manual.')
		add(abs(v['pv'] - v['sp']) <= cfg['steady_band'], 'PV is steady at SP (%.1f %s off; needs %.0f or less)' % (v['pv'] - v['sp'], u, cfg['steady_band']),
			'PV is %.1f degrees from SP; wait until it is steady.' % (v['pv'] - v['sp']))
		add(v['pv'] + 2.0 * bump + 8.0 <= v['hl'], 'Room below the high limit (%.0f)' % v['hl'], 'Too close to the high limit (%.0f): PV %.1f.' % (v['hl'], v['pv']))
		add(bump < 0.6 * v['soak_to_fast'], 'Bump (%.1f) stays under the Fast PID switch (%.1f)' % (bump, v['soak_to_fast']),
			'A bump of %.1f would switch the zone to the Fast PID (switch at %.1f).' % (bump, v['soak_to_fast']))
		add(bump < 0.6 * v['dev'], 'Bump (%.1f) stays under the SP-deviation warning (%.1f)' % (bump, v['dev']),
			'A bump of %.1f would raise the SP-deviation warning (at %.1f).' % (bump, v['dev']))
	else:
		add(None, 'Line is running normally with material; nobody is splicing, indexing or changing speed', None)
		add(abs(v['sp'] - v['sp_w']) <= 0.05, 'SP has settled (active %.1f, commanded %.1f)' % (v['sp'], v['sp_w']),
			'The SP is still changing (active %.1f, commanded %.1f). Wait a few seconds and try again.' % (v['sp'], v['sp_w']))
		add(bool(v['line_running']), 'Line is running', 'The line is not running.')
		add(bool(v['active']), '%s tension control is active' % cfg['label'], '%s tension control is not active.' % cfg['label'])
		add(not v['swm'], 'The PID is in auto (not manual)', 'The PID is in manual.')
		for k in _off_keys(cfg):
			add(not v[k], cfg[k + '_text'], cfg[k + '_text'].replace('is not', 'is') + ' (it must not be).')
		add(abs(v['pv'] - v['sp']) <= cfg['steady_band'], 'Tension is steady at SP (%.1f %s off; needs %.0f or less)' % (v['pv'] - v['sp'], u, cfg['steady_band']),
			'Tension is %.1f %s from SP; wait until it is steady.' % (v['pv'] - v['sp'], u))
		add(None, 'Fast tag group: PV, SP and output update every 0.25 s or faster (checked when the test starts)', None)
	add(cfg['bump_min'] <= bump <= cfg['bump_max'], 'Bump size %.1f is within %.1f to %.1f %s' % (bump, cfg['bump_min'], cfg['bump_max'], u),
		'Bump must be between %.1f and %.1f %s.' % (cfg['bump_min'], cfg['bump_max'], u))
	return items, v

def readiness(loop_id, mode, bump):
	"""The checklist for the page: [{'text', 'ok'}], ok = True / False / None."""
	if not supported(loop_id) or mode not in modes_for(loop_id):
		return [{'text': 'This test is not available for this loop.', 'ok': False}]
	try:
		cfg = loop_config(loop_id, mode)
		items, v = _checks(cfg, mode, float(bump or 0.0), bool(_state().get('running')))
	except Exception, e:
		return [{'text': 'The checks could not run: %s' % e, 'ok': False}]
	return [{'text': i['text'], 'ok': i['ok']} for i in items]

def precheck(cfg, mode, bump, busy=False):
	"""Problems that stop a test from starting (empty list = OK) and the values read."""
	items, v = _checks(cfg, mode, bump, busy)
	return [i['fail'] for i in items if i['ok'] is False], v

# ---------------------------------------------------------------- shared sampling loop
def _write_sp(cfg, value):
	rs = system.tag.writeBlocking([cfg['sp_w']], [float(value)])
	if not rs[0].isGood():
		raise AbortTest('SP write to the PLC failed (%s).' % rs[0])

def _make_ctx(cfg, s, run_id, mode):
	keys = ['pv', 'sp', 'sp_w', 'cv'] + (['status', 'faults_ok', 'auto'] if cfg['kind'] == 'temperature' else ['active', 'line_running', 'swm'] + _off_keys(cfg))
	if mode == 'heatup':
		keys = ['pv', 'sp', 'cv', 'status', 'faults_ok', 'auto', 'hl']
	return {'run_id': run_id, 'cfg': cfg, 's': s, 'mode': mode, 'keys': keys, 't0': time.time(), 'next': time.time(), 'bad': 0, 'sat': 0.0,
		'cmd': None, 'cmd_prev': None, 'cmd_t': 0.0, 'steps': [], 'pv_ts': [], 'data': {'t': [], 'sp': [], 'pv': [], 'cv': []}}

def _tick(ctx):
	"""Wait for the next sample, read the loop, run the guards, record. Returns the values, or None when this sample was unusable."""
	cfg, s = ctx['cfg'], ctx['s']
	delay = ctx['next'] - time.time()
	if delay > 0:
		time.sleep(delay)
	now = time.time()
	ctx['next'] += cfg['sample_s']
	if ctx['next'] < now - 5.0 * cfg['sample_s']:
		ctx['next'] = now  # fell behind: do not try to catch up
	if s.get('abort'):
		raise AbortTest('Aborted by %s.' % s.get('abort_by', 'the operator'))
	if s.get('finish') and ctx['mode'] == 'heatup' and ctx.get('heating'):
		raise EndCapture('Finished by the operator.')
	if now - ctx['t0'] > cfg['max_total_s']:
		raise AbortTest('The test took longer than %d s.' % cfg['max_total_s'])
	keys = ctx['keys']
	vals = _read_ts([cfg[k] for k in keys])
	if any((not good) or val is None for val, good, ts in vals):
		ctx['bad'] += 1
		if ctx['bad'] * cfg['sample_s'] >= 5.0:
			raise AbortTest('Tag quality was bad for 5 s.')
		return None
	ctx['bad'] = 0
	v = dict((k, val) for k, (val, good, ts) in zip(keys, vals))
	pv_ts = vals[keys.index('pv')][2]
	if pv_ts is not None and (not ctx['pv_ts'] or pv_ts != ctx['pv_ts'][-1]):
		ctx['pv_ts'].append(pv_ts)
	s['heartbeat'] = now
	s['pv'], s['sp'], s['cv'], s['elapsed'] = v['pv'], v['sp'], v['cv'], now - ctx['t0']
	ctx['guard'](ctx, v, now)
	if now - ctx.get('hb_t', 0.0) >= HB_EVERY_S:
		ctx['hb_t'] = now
		try:
			_db_heartbeat(ctx['run_id'])
		except Exception, e:
			_log.warn('heartbeat not stored: %s' % e)
	d = ctx['data']
	d['t'].append(round(now - ctx['t0'], 2))
	d['sp'].append(round(v['sp'], 3))
	d['pv'].append(round(v['pv'], 3))
	d['cv'].append(round(v['cv'], 3))
	return v

def _effective_dt(ctx):
	"""Median interval between PV tag updates (s), or None when the tag carries no usable timestamps."""
	ts = ctx['pv_ts']
	if len(ts) < 3:
		return None
	return _median([(ts[i] - ts[i - 1]) / 1000.0 for i in range(1, len(ts))])

# ---------------------------------------------------------------- steady-state test
def _guard_steady(ctx, v, now):
	cfg = ctx['cfg']
	if cfg['kind'] == 'temperature':
		if int(v['status']) != cfg['status_ok']:
			raise AbortTest('The zone left "Control to SP" (status %s).' % v['status'])
		if not v['faults_ok']:
			raise AbortTest('The zone reported a fault.')
		if not v['auto']:
			raise AbortTest('The control valve left auto.')
		if v['pv'] >= ctx['hl'] - 5.0:
			raise AbortTest('PV %.1f reached the high limit zone (%.0f).' % (v['pv'], ctx['hl']))
	else:
		if not v['line_running']:
			raise AbortTest('The line stopped.')
		if not v['active']:
			raise AbortTest('%s tension control is no longer active.' % cfg['label'])
		if v['swm']:
			raise AbortTest('The PID went to manual.')
		for k in _off_keys(cfg):
			if v[k]:
				raise AbortTest(cfg[k + '_text'].replace('is not', 'started') + ' during the test.')
	limit = 2.0 * ctx['bump'] + cfg['steady_band']
	if abs(v['pv'] - ctx['sp0']) > limit:
		raise AbortTest('PV %.1f strayed more than %.1f from the starting SP.' % (v['pv'], limit))
	if v['cv'] >= cfg['cv_max'] - 0.5 or v['cv'] <= cfg['cv_min'] + 0.5:
		ctx['sat'] += cfg['sample_s']
		if ctx['sat'] >= cfg['sat_abort_s']:
			raise AbortTest('CV was at its limit for %d s.' % cfg['sat_abort_s'])
	else:
		ctx['sat'] = 0.0
	if ctx['cmd'] is not None:
		if abs(v['sp_w'] - ctx['cmd']) > 0.05:
			raise ExternalChange('The SP input was changed by someone else (now %.1f, the test asked %.1f), for example a recipe download. The test stopped and left the SP alone.' % (v['sp_w'], ctx['cmd']))
		if now - ctx['cmd_t'] > 5.0 and abs(v['sp'] - ctx['cmd']) > 0.2:
			if ctx['cmd_prev'] is not None and abs(v['sp'] - ctx['cmd_prev']) <= 0.2:
				raise AbortTest('The PLC did not take the SP write (asked %.1f, active %.1f).' % (ctx['cmd'], v['sp']))
			raise ExternalChange('The active SP changed to %.1f, which the test did not ask for. The test stopped and left the SP alone.' % v['sp'])

def _segment(ctx, target, name, min_s, max_s, band, hold_s):
	"""Command SP = target and record until PV has been within 'band' of it for hold_s (and at least min_s)."""
	s, cfg = ctx['s'], ctx['cfg']
	s['phase'] = name
	if ctx['cmd'] is None or abs(ctx['cmd'] - target) > 1e-9:
		if name != 'baseline':
			ctx['steps'].append((len(ctx['data']['t']), target - ctx['cmd']))
		_db_heartbeat(ctx['run_id'], target)      # database first, then the PLC
		ctx['wrote'] = True
		_write_sp(cfg, target)
		ctx['cmd_prev'], ctx['cmd'], ctx['cmd_t'] = ctx['cmd'], target, time.time()
		_event(s, '%s: SP %.1f' % (name, target))
	start = time.time()
	inband = 0.0
	while True:
		v = _tick(ctx)
		if v is None:
			continue
		inband = inband + cfg['sample_s'] if abs(v['pv'] - target) <= band else 0.0
		el = time.time() - start
		if (el >= min_s and inband >= hold_s) or el >= max_s:
			return

def _restore(ctx, sp0, s):
	"""Put the original SP back, unless someone else has written the SP input in the meantime."""
	cfg = ctx['cfg']
	cur = _read([cfg['sp_w']])[0]
	if cur[1] and ctx['cmd'] is not None and abs(cur[0] - ctx['cmd']) > 0.05:
		_event(s, 'The SP input is %.1f, not the %.1f the test set: someone else changed it, so it was left alone.' % (cur[0], ctx['cmd']))
		s['restore_ok'] = True
		return True
	ok = False
	for attempt in range(3):
		try:
			_write_sp(cfg, sp0)
			time.sleep(1.5)
			v = _read([cfg['sp']])[0]
			if v[1] and abs(v[0] - sp0) < 0.05:
				ok = True
				break
		except Exception, e:
			_log.warn('SP restore attempt %d failed: %s' % (attempt + 1, e))
	s['restore_ok'] = ok
	if ok:
		_event(s, 'SP restored to %.1f' % sp0)
	else:
		_event(s, 'WARNING: could not confirm the SP restore to %.1f. Check the setpoint.' % sp0)
	return ok

def _probe_rate(ctx, seconds):
	"""Before touching anything: watch the PV tag for a few seconds and refuse when it updates too slowly for this loop."""
	cfg = ctx['cfg']
	end = time.time() + seconds
	while time.time() < end:
		v = _tick(ctx)
	eff = _effective_dt(ctx)
	max_dt = cal1615.tuning.PROFILES[cfg['kind']]['max_sample_s']
	if eff is None:
		raise AbortTest('The PV tag updated fewer than 3 times in %d s; this loop needs an update every %.2f s or faster. Put its tags on a faster tag group (see the README), then try again.' % (int(seconds), max_dt))
	if eff > max_dt:
		raise AbortTest('The PV tag updates every %.2f s but this loop needs %.2f s or faster. Put its tags on a faster tag group (see the README), then try again.' % (eff, max_dt))

def _worker_steady(cfg, bump, user, run_id, sp0, kp_cfg, hl):
	s = _state()
	ctx = _make_ctx(cfg, s, run_id, 'steady')
	ctx.update({'guard': _guard_steady, 'sp0': sp0, 'bump': bump, 'hl': hl})
	status, message = 'DONE', 'Test finished.'
	external = False
	try:
		band = max(0.25 * bump, cfg['band_min'])
		ctx['cmd'] = sp0
		if cfg['kind'] == 'tension':
			s['phase'] = 'checking tag speed'
			_probe_rate(ctx, 3.0)
		s['phase'] = 'baseline'
		_segment(ctx, sp0, 'baseline', cfg['base_min_s'], cfg['base_max_s'], band, cfg['hold_s'])
		for name, off in (('bump up', bump), ('back', 0.0), ('bump down', -bump), ('return', 0.0)):
			last = name == 'return'
			_segment(ctx, sp0 + off, name, cfg['ret_min_s'] if last else cfg['seg_min_s'], cfg['ret_max_s'] if last else cfg['seg_max_s'], band, cfg['hold_s'])
		s['phase'] = 'analyzing'
	except ExternalChange, e:
		status, message, external = 'ABORTED', str(e), True
		_event(s, 'STOPPED: %s' % message)
	except AbortTest, e:
		status, message = 'ABORTED', str(e)
		_event(s, 'ABORTED: %s' % message)
	except Exception, e:
		status, message = 'ERROR', 'Unexpected error: %s' % e
		_log.error('Tuning run failed', e)
	restored = True if (external or not ctx.get('wrote')) else _restore(ctx, sp0, s)   # nothing to put back when the SP was never written
	result = None
	try:
		d = ctx['data']
		d['mode'], d['gain_set'], d['loop_id'] = 'steady', cfg['gain_set'], cfg['id']
		d['dt_eff'] = _effective_dt(ctx)
		if status == 'DONE' and len(d['t']) > 100:
			loop = dict(cfg)
			loop['dt_eff'] = d['dt_eff']
			dt = (d['t'][-1] - d['t'][0]) / max(len(d['t']) - 1, 1)
			if ctx['steps']:
				k, dsp = ctx['steps'][0]
				chk = cal1615.tuning.scale_check(d['cv'], k, dsp, kp_cfg['kp'], loop['pv_max'] - loop['pv_min'])
				d['scale_check'] = chk
				if chk['error_pct'] is not None and chk['error_pct'] != cfg['error_pct']:
					d['convention_mismatch'] = True
					loop['error_pct'] = chk['error_pct']
			res = cal1615.tuning.analyze(loop, dt, d['sp'], d['pv'], d['cv'], current=kp_cfg)
			d['analysis'] = res
			d['current'] = kp_cfg
			d['orig_sp'], d['bump'] = sp0, bump
			if d.get('convention_mismatch'):
				res['quality']['warnings'].append('The PLC PID appears to work on %s error, not on %s as configured; gains were calculated for what was measured but must not be applied until this is resolved.' % (
					'percent of span' if loop['error_pct'] else 'engineering units', 'percent of span' if cfg['error_pct'] else 'engineering units'))
			elif d.get('scale_check', {}).get('error_pct') is None:
				res['quality']['warnings'].append('The PID error form could not be verified from this test (%s); the PLC data says it works in %s.' % (
					d.get('scale_check', {}).get('why', 'no SP step'), 'percent of span' if cfg['error_pct'] else 'engineering units'))
			result = res
		_db_finish(run_id, status if restored else 'ERROR', message if restored else message + ' SP RESTORE NOT CONFIRMED.', d)
	except Exception, e:
		_log.error('Tuning analysis failed', e)
		status, message = 'ERROR', 'Analysis failed: %s' % e
		try:
			_db_finish(run_id, 'ERROR', message, ctx['data'])
		except Exception, e2:
			_log.error('Could not store the run', e2)
	s['result'], s['status'], s['message'] = result, status, message
	s['phase'] = 'idle'
	s['running'] = False
	_event(s, 'Finished: %s' % status)

# ---------------------------------------------------------------- heat-up capture (passive: nothing is written)
def _guard_heatup(ctx, v, now):
	cfg, s = ctx['cfg'], ctx['s']
	st = int(v['status'])
	if not ctx.get('heating'):
		if not v['faults_ok']:
			raise AbortTest('The zone reports a fault.')
		if v['cv'] >= 5.0:
			ctx['heating'], ctx['on_t'], ctx['inband'] = True, now, 0.0
			s['phase'] = 'heating'
			_event(s, 'Heat started: valve output %.0f %%, PV %.1f' % (v['cv'], v['pv']))
		elif now - ctx['t0'] > cfg['arm_timeout_s']:
			raise AbortTest('The heat did not start within %d minutes.' % int(cfg['arm_timeout_s'] / 60))
		return
	if st not in HEATING:
		raise EndCapture('The zone stopped heating (status %s).' % _status_text(st))
	if not v['faults_ok']:
		raise EndCapture('The zone reported a fault.')
	if not v['auto']:
		raise EndCapture('The valve left auto.')
	if v['pv'] >= v['hl'] - 5.0:
		raise EndCapture('PV reached the high-limit zone (%.0f).' % v['hl'])
	ctx['inband'] = ctx['inband'] + cfg['sample_s'] if abs(v['pv'] - v['sp']) <= cfg['reach_band'] else 0.0
	if ctx['inband'] >= cfg['reach_hold_s']:
		raise EndCapture('PV has been at SP for %d minutes.' % int(cfg['reach_hold_s'] / 60))
	if now - ctx['on_t'] > cfg['max_heat_s']:
		raise EndCapture('%d minutes of heating captured.' % int(cfg['max_heat_s'] / 60))

def _worker_heatup(cfg, user, run_id, kp_cfg):
	s = _state()
	ctx = _make_ctx(cfg, s, run_id, 'heatup')
	ctx.update({'guard': _guard_heatup, 'heating': False})
	status, message = 'DONE', 'Capture finished.'
	try:
		s['phase'] = 'waiting for heat'
		while True:
			_tick(ctx)
	except EndCapture, e:
		message = str(e)
		_event(s, 'Capture ended: %s' % message)
	except AbortTest, e:
		status, message = 'ABORTED', str(e)
		_event(s, 'ABORTED: %s' % message)
	except Exception, e:
		status, message = 'ERROR', 'Unexpected error: %s' % e
		_log.error('Heat-up capture failed', e)
	s['phase'] = 'analyzing'
	result = None
	try:
		d = ctx['data']
		d['mode'], d['gain_set'], d['loop_id'] = 'heatup', cfg['gain_set'], cfg['id']
		d['dt_eff'] = _effective_dt(ctx)
		if status == 'DONE':
			loop = dict(cfg)
			loop['dt_eff'] = d['dt_eff']
			dt = (d['t'][-1] - d['t'][0]) / max(len(d['t']) - 1, 1) if len(d['t']) > 1 else cfg['sample_s']
			res = cal1615.tuning.analyze_heatup(loop, dt, d['sp'], d['pv'], d['cv'], current=kp_cfg)
			if 'error' in res:
				status, message = 'ABORTED', res['error']
			else:
				res['quality']['warnings'].append('The PLC PID error form was not measured in a heat-up; the PLC data says it works in %s.' % ('percent of span' if cfg['error_pct'] else 'engineering units'))
				res['capture_end'] = message
				d['analysis'] = res
				d['current'] = kp_cfg
				d['assumed_convention'] = True
				result = res
		_db_finish(run_id, status, message, d)
	except Exception, e:
		_log.error('Heat-up analysis failed', e)
		status, message = 'ERROR', 'Analysis failed: %s' % e
		try:
			_db_finish(run_id, 'ERROR', message, ctx['data'])
		except Exception, e2:
			_log.error('Could not store the run', e2)
	s['result'], s['status'], s['message'] = result, status, message
	s['phase'] = 'idle'
	s['running'] = False
	_event(s, 'Finished: %s' % status)

# ---------------------------------------------------------------- called by the page
def start(loop_id, bump, user, mode='steady'):
	"""Start a test (or arm a heat-up capture). Returns (started, message)."""
	s = _state()
	recover()
	if s.get('running'):
		return False, 'A test is already running on %s.' % s.get('loop')
	if not user:
		return False, 'Log in first.'
	if not supported(loop_id):
		return False, 'The tuning test is not available for this loop.'
	if mode not in modes_for(loop_id):
		return False, '%s is not available for this loop.' % MODE_NAMES.get(mode, mode)
	s['running'] = True  # claim it before the slow checks so two sessions cannot both start
	try:
		cfg = loop_config(loop_id, mode)
		bump = float(bump or 0.0)
		problems, v = precheck(cfg, mode, bump)
		if problems:
			s['running'] = False
			return False, ' '.join(problems)
		kp = {'kp': float(v['kp']), 'ki': float(v['ki']), 'kd': float(v['kd'])}
		sp0 = float(v['sp']) if mode == 'steady' else None
		run_id = _db_insert(loop_id, user, sp0, cfg['sp_w'], bump if mode == 'steady' else None, mode)
		s.update({'abort': False, 'finish': False, 'loop': loop_id, 'user': user, 'run_id': run_id, 'mode': mode, 'phase': 'starting', 'orig_sp': sp0,
			'bump': bump, 'result': None, 'status': 'RUNNING', 'message': '', 'heartbeat': time.time(), 'restore_ok': None, 'events': []})
		if mode == 'heatup':
			_event(s, '%s armed a heat-up capture on %s: PV %.1f, SP %.1f. Start the heat now.' % (user, loop_id, v['pv'], v['sp']))
			system.util.invokeAsynchronous(_worker_heatup, [cfg, user, run_id, kp])
		else:
			_event(s, '%s started a test on %s: SP %.1f, bump %.1f' % (user, loop_id, sp0, bump))
			system.util.invokeAsynchronous(_worker_steady, [cfg, bump, user, run_id, sp0, kp, float(v['hl']) if 'hl' in v else 0.0])
	except Exception, e:
		s['running'] = False
		_log.error('Could not start the tuning test', e)
		return False, 'Could not start the test: %s' % e
	return True, 'Capture armed. Press Start Heat on the zone.' if mode == 'heatup' else 'Test started.'

def abort(user):
	"""Stop and discard the running test; an SP bump is restored."""
	s = _state()
	if s.get('running'):
		s['abort'], s['abort_by'] = True, user or 'the operator'
		return True
	return False

def finish(user):
	"""Heat-up capture: stop recording now and analyse what was captured."""
	s = _state()
	if s.get('running') and s.get('mode') == 'heatup':
		s['finish'] = True
		return True
	return False

def status():
	"""Plain dict for the page."""
	s = _state()
	keys = ['running', 'phase', 'mode', 'loop', 'user', 'status', 'message', 'pv', 'sp', 'cv', 'elapsed', 'orig_sp', 'bump', 'restore_ok', 'events']
	return dict((k, s.get(k)) for k in keys)

def last(loop_id):
	"""Latest finished run of a loop (from the database), or None."""
	return _db_last(loop_id)

def recover():
	"""Clean up a test whose thread died (gateway restart, crash). Safe to call any time. A heat-up capture is just marked lost
	(nothing was written). An SP bump is put back, unless the SP is no longer the value the test commanded (someone else changed it)."""
	s = _state()
	try:
		rows = _db_running()
	except:
		return 'recover: database not available (%s)' % sys.exc_info()[1]
	out = []
	for r in rows:
		if r['age'] < HB_STALE_S:
			continue  # a live test (its heartbeat is recent)
		if r['mode'] == 'heatup' or r['orig_sp'] is None:
			msg = 'Interrupted heat-up capture: the capture was lost. Nothing had been written to the PLC.'
		else:
			cur = system.tag.readBlocking([r['sp_tag']])[0]
			last_cmd = r['last_cmd'] if r['last_cmd'] is not None else r['orig_sp']
			if not (cur.quality.isGood() and cur.value is not None):
				msg = 'Interrupted test: the SP could not be read, so it was not touched. Check the setpoint.'
			elif abs(cur.value - r['orig_sp']) <= 0.05:
				msg = 'Interrupted test: SP was already %.1f.' % r['orig_sp']
			elif abs(cur.value - last_cmd) > 0.05:
				msg = 'Interrupted test: the SP is now %.1f, not the %.1f the test set. Someone else changed it, so it was not touched.' % (cur.value, last_cmd)
			else:
				system.tag.writeBlocking([r['sp_tag']], [r['orig_sp']])
				msg = 'Interrupted test: SP put back to %.1f (was %.1f).' % (r['orig_sp'], cur.value)
		_db_finish(r['id'], 'RECOVERED' if r['mode'] != 'heatup' and r['orig_sp'] is not None else 'ABORTED', msg, None)
		_log.warn(msg)
		out.append(msg)
		if s.get('running') and s.get('run_id') == r['id']:
			s['running'] = False
	return '; '.join(out)

# ---------------------------------------------------------------- apply / revert the suggested gains
# Only Kp and Ki are changed. The suggestion is PI, and overwriting a Kd that someone set by hand would change the loop.
APPLY_MIN_RATIO = 0.2   # a suggestion more than 5x away from the current gain is refused: the model is probably wrong
APPLY_MAX_RATIO = 5.0

def _fmt(v, f='%.3f'):
	return '---' if v is None else f % v

def _gains_now(cfg):
	"""Gains the PLC is using now (read back from the parameter tags the HMI inputs are loaded into)."""
	v = _read([cfg['kp'], cfg['ki']])
	if not (v[0][1] and v[1][1]) or v[0][0] is None or v[1][0] is None:
		return None
	return float(v[0][0]), float(v[1][0])

def _apply_blockers(run, cur_kp, cur_ki, kind='temperature'):
	"""Reasons the suggested gains must not be applied (empty list = OK)."""
	why = []
	d = run['data'] if run else None
	if not run or run['status'] != 'DONE' or not d or not d.get('analysis'):
		return ['There is no finished test to apply.']
	a = d['analysis']
	mode = d.get('mode', 'steady')
	if d.get('convention_mismatch'):
		why.append('The PID error form measured in the test differs from the configured one, so the gain numbers cannot be trusted.')
	if a['model']['r2'] < 0.8:
		why.append('The model fits the data poorly (R2 %.2f).' % a['model']['r2'])
	if a['quality']['snr'] < 15.0:
		why.append('The PV barely moved compared with the noise.')
	if mode == 'steady' and a['quality']['saturated_fraction'] > 0.05:
		why.append('CV was at its limit during the test.')
	if a['model']['K'] < 0:
		why.append('The process responds the wrong way (negative gain); check the PID action.')
	if not a['suggested_metrics']['stable']:
		why.append('The suggested gains are not stable on the fitted model.')
	max_dt = cal1615.tuning.PROFILES[kind]['max_sample_s']
	if d.get('dt_eff') is not None and d['dt_eff'] > max_dt:
		why.append('The PV tag updated only every %.2f s (this loop needs %.2f s or faster).' % (d['dt_eff'], max_dt))
	cur = d.get('current') or {}
	if cur and (abs(cur.get('kp', 0) - cur_kp) > 1e-6 + 0.001 * abs(cur_kp) or abs(cur.get('ki', 0) - cur_ki) > 1e-9 + 0.001 * abs(cur_ki)):
		why.append('The gains were changed after the test (now Kp %.3f, Ki %.4f; tested with Kp %.3f, Ki %.4f). Run a new test.' % (cur_kp, cur_ki, cur.get('kp', 0), cur.get('ki', 0)))
	s = a['suggested']
	for name, new, old in (('Kp', s['kp'], cur_kp), ('Ki', s['ki'], cur_ki)):
		if old > 0 and not (APPLY_MIN_RATIO <= new / old <= APPLY_MAX_RATIO):
			why.append('Suggested %s %.4g is more than 5 times different from the current %.4g.' % (name, new, old))
	return why

def _cfg_of_run(loop_id, run):
	d = run['data'] or {}
	return loop_config(loop_id, d.get('mode', 'steady'))

def summary(loop_id, running=None):
	"""Display strings for the page; an internal error is reported as text instead of leaving the card blank."""
	try:
		return _summary(loop_id)
	except:
		e = sys.exc_info()[1]
		_log.warn('summary failed: %s' % e)
		return {'has_run': False, 'text': 'The last result could not be read: %s' % e, 'can_apply': False, 'can_revert': False, 'blockers': '', 'warnings': '', 'applied': ''}

def _summary(loop_id):
	"""Flat dict of display strings for the page (cheap enough to poll). 'running' is only there so the page refreshes it when a test starts or ends."""
	out = {'has_run': False, 'text': 'No test has been run on this loop yet.', 'can_apply': False, 'can_revert': False, 'blockers': '', 'warnings': '', 'applied': ''}
	if not supported(loop_id):
		out['text'] = ''
		return out
	try:
		run = _db_last(loop_id)
		ap = _db_last_apply(loop_id)
	except Exception, e:
		out['text'] = 'Test results are not available (database: %s).' % e
		return out
	if ap:
		out['can_revert'] = True
		out['applied'] = 'Applied by %s to the %s: Kp %.3f -> %.3f, Ki %.4f -> %.4f.' % (ap['user'], set_label(loop_id, ap['gain_set']), ap['old_kp'], ap['new_kp'], ap['old_ki'], ap['new_ki'])
	if not run:
		return out
	out['has_run'] = True
	out['run_id'] = run['id']
	out['status'] = run['status']
	d = run['data']
	if run['status'] != 'DONE' or not d or not d.get('analysis'):
		out['text'] = 'Last test: %s. %s' % (run['status'], run['message'] or '')
		return out
	a = d['analysis']
	m, s, cm, sm = a['model'], a['suggested'], a['current_metrics'], a['suggested_metrics']
	mode = d.get('mode', 'steady')
	gs = d.get('gain_set', 'pid2')
	extra = ''
	if mode == 'heatup' and a.get('tangent'):
		t = a['tangent']
		extra = 'Steepest rise %.2f %% of span per minute, apparent dead time %.0f s. Tangent (Ziegler-Nichols, halved): Kp %.3f, Ki %.4f.' % (
			t['slope_pct_per_s'] * 60.0, t['dead_time'], a['coarse']['kp'], a['coarse']['ki'])
	out.update({
		'text': 'Last test (run %d): %s, tuned the %s' % (run['id'], MODE_NAMES.get(mode, mode), set_label(loop_id, gs)),
		'k': _fmt(m['K']), 'tau': _fmt(m['tau'], '%.0f s'), 'theta': _fmt(m['theta'], '%.0f s'), 'r2': _fmt(m['r2'], '%.3f'),
		'convention': 'assumed from the PLC data (engineering units)' if d.get('assumed_convention') else
			{True: 'percent of span', False: 'engineering units', None: 'not detected'}[d.get('scale_check', {}).get('error_pct')],
		'cur_kp': _fmt(d.get('current', {}).get('kp')), 'cur_ki': _fmt(d.get('current', {}).get('ki'), '%.4f'),
		'sug_kp': _fmt(s['kp']), 'sug_ki': _fmt(s['ki'], '%.4f'),
		'cur_perf': ('overshoot %.0f %%, settles in %.0f s' % (cm['overshoot_pct'], cm['settle_s'])) if cm['stable'] else 'unstable on the model',
		'sug_perf': ('overshoot %.0f %%, settles in %.0f s' % (sm['overshoot_pct'], sm['settle_s'])) if sm['stable'] else 'unstable on the model',
		'warnings': ' '.join(a['quality']['warnings']), 'extra': extra, 'mode': mode, 'gain_set': gs,
	})
	try:
		cfg = _cfg_of_run(loop_id, run)
		now = _gains_now(cfg)
		if now is not None:
			blockers = _apply_blockers(run, now[0], now[1], cfg['kind'])
			out['blockers'] = ' '.join(blockers)
			out['can_apply'] = not blockers
	except Exception, e:
		out['blockers'] = 'Cannot read the current gains (%s).' % e
	return out

def _write_gains(kp_w, ki_w, kp, ki):
	rs = system.tag.writeBlocking([kp_w, ki_w], [float(kp), float(ki)])
	return all(r.isGood() for r in rs)

def _wait_gains(cfg, kp, ki, seconds=6.0):
	"""True when the PLC reports the new gains (the HMI input is copied into the parameter every scan)."""
	end = time.time() + seconds
	while True:
		g = _gains_now(cfg)
		if g is not None and abs(g[0] - kp) <= 0.002 * max(abs(kp), 1e-9) and abs(g[1] - ki) <= 0.002 * max(abs(ki), 1e-9):
			return True
		if time.time() >= end:
			return False
		time.sleep(0.5)

def apply_suggested(loop_id, user):
	"""Write the suggested Kp / Ki of the last finished test to the gain set it was measured for. Returns (ok, message)."""
	s = _state()
	if not user:
		return False, 'Log in first.'
	if not supported(loop_id):
		return False, 'The tuning test is not available for this loop.'
	if s.get('running'):
		return False, 'A test is running.'
	run = _db_last(loop_id)
	if not run or not run['data']:
		return False, 'There is no finished test to apply.'
	cfg = _cfg_of_run(loop_id, run)
	now = _gains_now(cfg)
	if now is None:
		return False, 'Cannot read the current gains.'
	blockers = _apply_blockers(run, now[0], now[1], cfg['kind'])
	if blockers:
		return False, ' '.join(blockers)
	sug = run['data']['analysis']['suggested']
	if not _write_gains(cfg['kp_w'], cfg['ki_w'], sug['kp'], sug['ki']):
		_write_gains(cfg['kp_w'], cfg['ki_w'], now[0], now[1])
		return False, 'The PLC did not take the gains. The old gains were written back.'
	if not _wait_gains(cfg, sug['kp'], sug['ki']):
		_write_gains(cfg['kp_w'], cfg['ki_w'], now[0], now[1])
		return False, 'The PLC did not report the new gains within 6 s. The old gains were written back.'
	_db_insert_apply(run['id'], loop_id, user, cfg['gain_set'], now[0], now[1], sug['kp'], sug['ki'])
	msg = '%s applied Kp %.3f, Ki %.4f to the %s of %s (was Kp %.3f, Ki %.4f).' % (user, sug['kp'], sug['ki'], set_label(loop_id, cfg['gain_set']), loop_id, now[0], now[1])
	_log.info(msg)
	return True, msg

def revert_applied(loop_id, user):
	"""Put the gains back that were replaced by the last Apply. Returns (ok, message)."""
	s = _state()
	if not user:
		return False, 'Log in first.'
	if not supported(loop_id):
		return False, 'The tuning test is not available for this loop.'
	if s.get('running'):
		return False, 'A test is running.'
	ap = _db_last_apply(loop_id)
	if not ap:
		return False, 'Nothing to revert on this loop.'
	r = _reg(loop_id)
	g = r['gains']
	gs = ap['gain_set']
	cfg = {'kp': g[gs + '_kp'], 'ki': g[gs + '_ki']}
	if not _write_gains(g[gs + '_kp_w'], g[gs + '_ki_w'], ap['old_kp'], ap['old_ki']):
		return False, 'The PLC did not take the old gains.'
	if not _wait_gains(cfg, ap['old_kp'], ap['old_ki']):
		return False, 'The PLC did not report the old gains within 6 s. Check Kp and Ki on this page.'
	_db_mark_reverted(ap['id'], user)
	msg = '%s reverted the %s of %s to Kp %.3f, Ki %.4f.' % (user, set_label(loop_id, gs), loop_id, ap['old_kp'], ap['old_ki'])
	_log.info(msg)
	return True, msg
