SELECT name,
	[zone_1__recirc_sp],
	[zone_1__exhaust_sp],
	[zone_1__temp_sp],
	[zone_2__recirc_sp],
	[zone_2__exhaust_sp],
	[zone_2__temp_sp],
	[zone_3__recirc_sp],
	[zone_3__exhaust_sp],
	[zone_3__temp_sp],
	[line_speed_sp],
	[letoff_tension_sp],
	[acc_tension_sp],
	[acc_fill_pressure_sp],
	[acc_counter_pressure_sp],
	[cure_time_sp],
	[platen_temp_sp],
	[impreg_gap_sp],
	[impreg_gap_ds_offset_sp],
	[impreg_gap_os_offset_sp],
	[impreg_supply_speed_sp],
	[ts1_mode_sp],
	[ts1_tension_sp],
	[ts1_stretch_sp],
	[slitter_speed_sp],
	[adv_cooling_temp_sp],
	[ts2_tension_sp],
	[lower_poly_tension_sp],
	[lower_poly_b_tension_sp],
	[upper_poly_tension_sp],
	[upper_poly_b_tension_sp],
	[winder_tension_sp],
	[winder_mode_sp],
	[winder_torque_sp],
	[tension_deviation_sp]
FROM dbo.rcp_cal1615
WHERE name = :name