# Tunable PID loops for the PID Tuning page (Maintenance/PID Tuning, route /pid-tuning). Generated by tools/pid_tuning.js.
# The PLC runs classic PID instructions. Gains are PLC parameters (pNN_param_pidX_*); the HMI writes them to
# p02_real_from_hmi.<section>[44..51] and the PLC loads them into the PID (KP/KI/KD/BIAS).
# Gain keys follow cal1615.zones: pid1_kp / pid1_kp_w (read / write), ... pid2_bias. An empty path hides that row.
LOOPS = {
	'zone1': {
		'label': 'Zone 1 Temperature', 'units': 'F',
		'pv': '[cal1615]p11_real_to_hmi_2_', 'sp': '[cal1615]p11r30_pid_temp_sp', 'cv': '[cal1615]p11_ao_cv',
		'set1': 'Fast PID (heat-up)', 'set2': 'Auto PID (control)', 'gains': cal1615.zones.PATHS[1],
		'valve_view': 'Components/Oven/Zone/Control Valve', 'valve_params': {'zone': 1},
	},
	'zone2': {
		'label': 'Zone 2 Temperature', 'units': 'F',
		'pv': '[cal1615]p12_real_to_hmi_2_', 'sp': '[cal1615]p12r30_pid_temp_sp', 'cv': '[cal1615]p12_ao_cv',
		'set1': 'Fast PID (heat-up)', 'set2': 'Auto PID (control)', 'gains': cal1615.zones.PATHS[2],
		'valve_view': 'Components/Oven/Zone/Control Valve', 'valve_params': {'zone': 2},
	},
	'zone3': {
		'label': 'Zone 3 Temperature', 'units': 'F',
		'pv': '[cal1615]p13_real_to_hmi_2_', 'sp': '[cal1615]p13r30_pid_temp_sp', 'cv': '[cal1615]p13_ao_cv',
		'set1': 'Fast PID (heat-up)', 'set2': 'Auto PID (control)', 'gains': cal1615.zones.PATHS[3],
		'valve_view': 'Components/Oven/Zone/Control Valve', 'valve_params': {'zone': 3},
	},
	'cooling': {
		'label': 'Advanced Cooling Temperature', 'units': 'F',
		'pv': '[cal1615]p19_ai_tc01', 'sp': '[cal1615]p01_recipe_active/adv_cooling_temp_sp', 'cv': '[cal1615]p19_ao_cv',
		'set1': '', 'set2': 'Auto PID (control)',
		'gains': {  # the P19 PID uses only the second gain set
			'pid2_kp': '[cal1615]p19_param_pid2_kp', 'pid2_kp_w': '[cal1615]p02_real_from_hmi/adv_cooling_48_',
			'pid2_ki': '[cal1615]p19_param_pid2_ki', 'pid2_ki_w': '[cal1615]p02_real_from_hmi/adv_cooling_49_',
			'pid2_kd': '[cal1615]p19_param_pid2_kd', 'pid2_kd_w': '[cal1615]p02_real_from_hmi/adv_cooling_50_',
			'pid2_bias': '[cal1615]p19_param_pid2_ff', 'pid2_bias_w': '[cal1615]p02_real_from_hmi/adv_cooling_51_',
		},
		'valve_view': 'Components/Oven/Roll Cooling Valve', 'valve_params': {},
	},
}
ORDER = ['zone1', 'zone2', 'zone3', 'cooling']
GAIN_KEYS = [s + '_' + g for s in ('pid1', 'pid2') for g in ('kp', 'ki', 'kd', 'bias')]

def loop(name):
	"""Flat dict of tag paths for one loop (missing gains -> '')."""
	l = LOOPS.get(name) or LOOPS['zone1']
	out = dict((k, v) for k, v in l.items() if k != 'gains')
	for k in GAIN_KEYS:
		out[k] = l['gains'].get(k, '')
		out[k + '_w'] = l['gains'].get(k + '_w', '')
	return out

def pens(name):
	"""Tuning trend: PV and SP on the top plot, controller output on the bottom plot."""
	l = LOOPS.get(name) or LOOPS['zone1']
	src = 'histprov:myOracle:/drv:ignition-4d950438c38c:cal1615:/tag:'
	def pen(label, tag, color, plot):
		st = lambda o: {'fill': {'color': color, 'opacity': o}, 'stroke': {'color': color, 'dashArray': 0, 'opacity': o, 'width': 1.5}}
		return {'axis': '', 'name': label, 'plot': plot, 'enabled': True, 'selectable': True, 'visible': True,
			'data': {'aggregateMode': 'default', 'source': src + tag.split(']', 1)[-1].lower()},
			'display': {'type': 'line', 'breakLine': True, 'interpolation': 'curveStepAfter' if plot else 'curveLinear', 'radius': 3,
				'styles': {'normal': st(0.9), 'highlighted': st(1), 'muted': st(0.4), 'selected': st(1)}}}
	return [pen('PV', l['pv'], '#1F77B4', 0), pen('SP', l['sp'], '#D62728', 0), pen('Output %', l['cv'], '#2CA02C', 1)]
