# Tunable PID loops: the registry for the PID Tuning page (Maintenance/PID Tuning, route /pid-tuning) and for the test runner
# cal1615.tunerun. Generated by tools/pid_tuning.js. Edit the generator, not this file.
#
# The PLC runs classic PID instructions with INDEPENDENT gains (Kp unitless, Ki 1/s, Kd s) on error in ENGINEERING UNITS
# (the PID data shows ERR = SP - PV in degrees / lb), so the gain numbers the tuner suggests are scaled for that ('error_pct' False).
# Oven zones: gains are PLC parameters (pNN_param_pidX_*); the HMI writes them to p02_real_from_hmi.<section>[44..51] and the PLC
# loads them into the PID. Zone 1 and 2 have a Fast PID (large error, heat-up) and an Auto PID (near SP); zone 3 and the cooling
# loop only use the Auto PID. Tension loops: gains are written to p02_real_from_hmi.<section>[40..42] and loaded into the PID every scan.
# Gain keys: pid1_kp / pid1_kp_w (read / write), ... pid2_bias. An empty path hides that row.
# The 'test' section is what cal1615.tunerun needs (tags, limits and timing); a loop without it has no tuning test.

def _zone_test(n, heat_set):
	p = cal1615.zones.PATHS[n]
	return {'kind': 'temperature', 'modes': ['heatup', 'steady'], 'heat_set': heat_set,
		'pv_min': 0.0, 'pv_max': 1000.0, 'cv_min': 0.0, 'cv_max': 100.0, 'error_pct': False,
		'pv': p['temp'], 'sp': p['temp_sp'], 'sp_w': p['temp_sp_w'], 'cv': p['cv_output'],
		'status': p['status'], 'status_ok': 10, 'faults_ok': p['led_zone_faults_ok'], 'auto': p['cv_auto'],
		'hl': p['tc_high_limit'], 'dev': p['sp_dev_warning'], 'soak_to_fast': p['soak_to_fast'],
		'sample_s': 1.0, 'bump_default': 3.0, 'bump_min': 1.0, 'bump_max': 8.0, 'steady_band': 3.0, 'band_min': 0.4,
		'base_min_s': 120.0, 'base_max_s': 600.0, 'seg_min_s': 240.0, 'seg_max_s': 900.0, 'ret_min_s': 120.0, 'ret_max_s': 300.0,
		'hold_s': 60.0, 'sat_abort_s': 30.0, 'max_total_s': 7200.0,
		'cold_margin': 40.0, 'arm_timeout_s': 1800.0, 'reach_band': 2.0, 'reach_hold_s': 180.0, 'max_heat_s': 7200.0}

LOOPS = {
	'zone1': {
		'label': 'Zone 1 Temperature', 'units': 'F',
		'pv': '[cal1615]p11_real_to_hmi_2_', 'sp': '[cal1615]p11r30_pid_temp_sp', 'cv': '[cal1615]p11_ao_cv',
		'set1': 'Fast PID (heat-up)', 'set2': 'Auto PID (control)', 'gains': cal1615.zones.PATHS[1],
		'valve_view': 'Components/Oven/Zone/Control Valve', 'valve_params': {'zone': 1},
		'test': _zone_test(1, 'pid1'),
	},
	'zone2': {
		'label': 'Zone 2 Temperature', 'units': 'F',
		'pv': '[cal1615]p12_real_to_hmi_2_', 'sp': '[cal1615]p12r30_pid_temp_sp', 'cv': '[cal1615]p12_ao_cv',
		'set1': 'Fast PID (heat-up)', 'set2': 'Auto PID (control)', 'gains': cal1615.zones.PATHS[2],
		'valve_view': 'Components/Oven/Zone/Control Valve', 'valve_params': {'zone': 2},
		'test': _zone_test(2, 'pid1'),
	},
	'zone3': {
		'label': 'Zone 3 Temperature', 'units': 'F',
		'pv': '[cal1615]p13_real_to_hmi_2_', 'sp': '[cal1615]p13r30_pid_temp_sp', 'cv': '[cal1615]p13_ao_cv',
		'set1': 'Fast PID (heat-up)', 'set2': 'Auto PID (control)', 'gains': cal1615.zones.PATHS[3],
		'valve_view': 'Components/Oven/Zone/Control Valve', 'valve_params': {'zone': 3},
		'test': _zone_test(3, 'pid2'),
	},
	'cooling': {
		'label': 'Advanced Cooling Temperature', 'units': 'F',
		'pv': '[cal1615]p19_ai_tc01', 'sp': '[cal1615]p01_recipe_active/adv_cooling_temp_sp', 'cv': '[cal1615]p19_ao_cv',
		'set1': '', 'set2': 'Auto PID (control)',
		'gains': {  # the P19 PID uses only the second gain set
			'pid2_kp': '[cal1615]p19_param_pid2_kp', 'pid2_kp_w': '[cal1615]p02_real_from_hmi/adv_cooling_48_',
			'pid2_ki': '[cal1615]p19_param_pid2_ki', 'pid2_ki_w': '[cal1615]p02_real_from_hmi/adv_cooling_49_',
			'pid2_kd': '[cal1615]p19_param_pid2_kd', 'pid2_kd_w': '[cal1615]p02_real_from_hmi/adv_cooling_50_',
			'pid2_bias': '[cal1615]p19_param_pid2_ff', 'pid2_bias_w': '[cal1615]p02_real_from_hmi/adv_cooling_51_',
		},
		'valve_view': 'Components/Oven/Roll Cooling Valve', 'valve_params': {},
	},
	'letoff': {'label': 'Let-Off Tension', 'units': 'LBS', 'pv': '[cal1615]p20r10_pid_tens/PV', 'sp': '[cal1615]p20r10_pid_tens/SP', 'cv': '[cal1615]p20r10_pid_tens/OUT', 'set1': '', 'set2': 'Gains', 'gains': {'pid2_kp': '[cal1615]p20r10_pid_tens/KP', 'pid2_ki': '[cal1615]p20r10_pid_tens/KI', 'pid2_kd': '[cal1615]p20r10_pid_tens/KD', 'pid2_kp_w': '[cal1615]p02_real_from_hmi/letoff_40_', 'pid2_ki_w': '[cal1615]p02_real_from_hmi/letoff_41_', 'pid2_kd_w': '[cal1615]p02_real_from_hmi/letoff_42_'}, 'valve_view': '', 'valve_params': {}, 'test': {'kind': 'tension', 'modes': ['steady'], 'pv_min': 0, 'pv_max': 500, 'cv_min': 0, 'cv_max': 100, 'error_pct': False, 'sample_s': 0.1, 'bump_default': 2, 'bump_min': 0.5, 'bump_max': 5, 'steady_band': 3, 'band_min': 0.4, 'base_min_s': 15, 'base_max_s': 60, 'seg_min_s': 20, 'seg_max_s': 60, 'ret_min_s': 15, 'ret_max_s': 60, 'hold_s': 5, 'sat_abort_s': 5, 'max_total_s': 900, 'pv': '[cal1615]p20r10_pid_tens/PV', 'sp': '[cal1615]p20r10_pid_tens/SP', 'sp_w': '[cal1615]p02_recipe_from_hmi/letoff_tension_sp', 'cv': '[cal1615]p20r10_pid_tens/OUT', 'active': '[cal1615]p20r10_tension_request', 'line_running': '[cal1615]p01r13_line_running', 'swm': '[cal1615]p20r10_pid_tens/SWM'}},
	'ts1': {'label': 'Tension Stand 1 Tension', 'units': 'LBS', 'pv': '[cal1615]p22r10_pid_psn/PV', 'sp': '[cal1615]p22r10_pid_psn/SP', 'cv': '[cal1615]p22r10_pid_psn/OUT', 'set1': '', 'set2': 'Gains', 'gains': {'pid2_kp': '[cal1615]p22r10_pid_psn/KP', 'pid2_ki': '[cal1615]p22r10_pid_psn/KI', 'pid2_kd': '[cal1615]p22r10_pid_psn/KD', 'pid2_kp_w': '[cal1615]p02_real_from_hmi/ts1_40_', 'pid2_ki_w': '[cal1615]p02_real_from_hmi/ts1_41_', 'pid2_kd_w': '[cal1615]p02_real_from_hmi/ts1_42_'}, 'valve_view': '', 'valve_params': {}, 'test': {'kind': 'tension', 'modes': ['steady'], 'pv_min': 0, 'pv_max': 500, 'cv_min': 0, 'cv_max': 100, 'error_pct': False, 'sample_s': 0.1, 'bump_default': 3, 'bump_min': 0.5, 'bump_max': 8, 'steady_band': 3, 'band_min': 0.4, 'base_min_s': 15, 'base_max_s': 60, 'seg_min_s': 20, 'seg_max_s': 60, 'ret_min_s': 15, 'ret_max_s': 60, 'hold_s': 5, 'sat_abort_s': 5, 'max_total_s': 900, 'pv': '[cal1615]p22r10_pid_psn/PV', 'sp': '[cal1615]p22r10_pid_psn/SP', 'sp_w': '[cal1615]p02_recipe_from_hmi/ts1_tension_sp', 'cv': '[cal1615]p22r10_pid_psn/OUT', 'active': '[cal1615]p22r11_request_tension', 'line_running': '[cal1615]p01r13_line_running', 'swm': '[cal1615]p22r10_pid_psn/SWM'}},
	'ts2': {'label': 'Tension Stand 2 Tension', 'units': 'LBS', 'pv': '[cal1615]p25r10_pid_psn/PV', 'sp': '[cal1615]p25r10_pid_psn/SP', 'cv': '[cal1615]p25r10_pid_psn/OUT', 'set1': '', 'set2': 'Gains', 'gains': {'pid2_kp': '[cal1615]p25r10_pid_psn/KP', 'pid2_ki': '[cal1615]p25r10_pid_psn/KI', 'pid2_kd': '[cal1615]p25r10_pid_psn/KD', 'pid2_kp_w': '[cal1615]p02_real_from_hmi/ts2_40_', 'pid2_ki_w': '[cal1615]p02_real_from_hmi/ts2_41_', 'pid2_kd_w': '[cal1615]p02_real_from_hmi/ts2_42_'}, 'valve_view': '', 'valve_params': {}, 'test': {'kind': 'tension', 'modes': ['steady'], 'pv_min': 0, 'pv_max': 500, 'cv_min': 0, 'cv_max': 100, 'error_pct': False, 'sample_s': 0.1, 'bump_default': 3, 'bump_min': 0.5, 'bump_max': 8, 'steady_band': 3, 'band_min': 0.4, 'base_min_s': 15, 'base_max_s': 60, 'seg_min_s': 20, 'seg_max_s': 60, 'ret_min_s': 15, 'ret_max_s': 60, 'hold_s': 5, 'sat_abort_s': 5, 'max_total_s': 900, 'pv': '[cal1615]p25r10_pid_psn/PV', 'sp': '[cal1615]p25r10_pid_psn/SP', 'sp_w': '[cal1615]p02_recipe_from_hmi/ts2_tension_sp', 'cv': '[cal1615]p25r10_pid_psn/OUT', 'active': '[cal1615]p25r10_tension_request', 'line_running': '[cal1615]p01r13_line_running', 'swm': '[cal1615]p25r10_pid_psn/SWM'}},
	'winder_a': {'label': 'Winder A Tension', 'units': 'LBS', 'pv': '[cal1615]p29r10_pid_psn/PV', 'sp': '[cal1615]p29r10_pid_psn/SP', 'cv': '[cal1615]p29r10_pid_psn/OUT', 'set1': '', 'set2': 'Gains', 'gains': {'pid2_kp': '[cal1615]p29r10_pid_psn/KP', 'pid2_ki': '[cal1615]p29r10_pid_psn/KI', 'pid2_kd': '[cal1615]p29r10_pid_psn/KD', 'pid2_kp_w': '[cal1615]p02_real_from_hmi/wdr_40_', 'pid2_ki_w': '[cal1615]p02_real_from_hmi/wdr_41_', 'pid2_kd_w': '[cal1615]p02_real_from_hmi/wdr_42_'}, 'valve_view': '', 'valve_params': {}, 'test': {'kind': 'tension', 'modes': ['steady'], 'pv_min': 0, 'pv_max': 500, 'cv_min': 0, 'cv_max': 100, 'error_pct': False, 'sample_s': 0.1, 'bump_default': 3, 'bump_min': 0.5, 'bump_max': 8, 'steady_band': 3, 'band_min': 0.4, 'base_min_s': 15, 'base_max_s': 60, 'seg_min_s': 20, 'seg_max_s': 60, 'ret_min_s': 15, 'ret_max_s': 60, 'hold_s': 5, 'sat_abort_s': 5, 'max_total_s': 900, 'pv': '[cal1615]p29r10_pid_psn/PV', 'sp': '[cal1615]p29r10_pid_psn/SP', 'sp_w': '[cal1615]p02_recipe_from_hmi/winder_tension_sp', 'cv': '[cal1615]p29r10_pid_psn/OUT', 'active': '[cal1615]p29r10_request_run', 'line_running': '[cal1615]p01r13_line_running', 'swm': '[cal1615]p29r10_pid_psn/SWM', 'must_be_off': [['[cal1615]p29_di_wdr_index_fwd', 'The winder is not indexing']]}},
	'winder_b': {'label': 'Winder B Tension', 'units': 'LBS', 'pv': '[cal1615]p29r11_pid_psn/PV', 'sp': '[cal1615]p29r11_pid_psn/SP', 'cv': '[cal1615]p29r11_pid_psn/OUT', 'set1': '', 'set2': 'Gains', 'gains': {'pid2_kp': '[cal1615]p29r11_pid_psn/KP', 'pid2_ki': '[cal1615]p29r11_pid_psn/KI', 'pid2_kd': '[cal1615]p29r11_pid_psn/KD', 'pid2_kp_w': '[cal1615]p02_real_from_hmi/wdr_40_', 'pid2_ki_w': '[cal1615]p02_real_from_hmi/wdr_41_', 'pid2_kd_w': '[cal1615]p02_real_from_hmi/wdr_42_'}, 'valve_view': '', 'valve_params': {}, 'test': {'kind': 'tension', 'modes': ['steady'], 'pv_min': 0, 'pv_max': 300, 'cv_min': 0, 'cv_max': 100, 'error_pct': False, 'sample_s': 0.1, 'bump_default': 3, 'bump_min': 0.5, 'bump_max': 8, 'steady_band': 3, 'band_min': 0.4, 'base_min_s': 15, 'base_max_s': 60, 'seg_min_s': 20, 'seg_max_s': 60, 'ret_min_s': 15, 'ret_max_s': 60, 'hold_s': 5, 'sat_abort_s': 5, 'max_total_s': 900, 'pv': '[cal1615]p29r11_pid_psn/PV', 'sp': '[cal1615]p29r11_pid_psn/SP', 'sp_w': '[cal1615]p02_recipe_from_hmi/winder_tension_sp', 'cv': '[cal1615]p29r11_pid_psn/OUT', 'active': '[cal1615]p29r11_request_run', 'line_running': '[cal1615]p01r13_line_running', 'swm': '[cal1615]p29r11_pid_psn/SWM', 'must_be_off': [['[cal1615]p29_di_wdr_index_fwd', 'The winder is not indexing']]}},
}
ORDER = ['zone1', 'zone2', 'zone3', 'cooling', 'letoff', 'ts1', 'ts2', 'winder_a', 'winder_b']
GAIN_KEYS = [s + '_' + g for s in ('pid1', 'pid2') for g in ('kp', 'ki', 'kd', 'bias')]

def loop(name):
	"""Flat dict of tag paths and settings for one loop (missing gains -> '') for the page."""
	l = LOOPS.get(name) or LOOPS['zone1']
	out = dict((k, v) for k, v in l.items() if k not in ('gains', 'test'))
	for k in GAIN_KEYS:
		out[k] = l['gains'].get(k, '')
		out[k + '_w'] = l['gains'].get(k + '_w', '')
	t = l.get('test')
	out['has_test'] = bool(t)
	out['kind'] = t['kind'] if t else 'temperature'
	out['modes'] = list(t['modes']) if t else []
	out['bump_default'] = t['bump_default'] if t else 3.0
	out['bump_min'] = t['bump_min'] if t else 1.0
	out['bump_max'] = t['bump_max'] if t else 8.0
	return out

def pens(name):
	"""Tuning trend: PV and SP on the top plot, controller output on the bottom plot."""
	l = LOOPS.get(name) or LOOPS['zone1']
	src = 'histprov:myOracle:/drv:ignition-4d950438c38c:cal1615:/tag:'
	def pen(label, tag, color, plot):
		st = lambda o: {'fill': {'color': color, 'opacity': o}, 'stroke': {'color': color, 'dashArray': 0, 'opacity': o, 'width': 1.5}}
		return {'axis': '', 'name': label, 'plot': plot, 'enabled': True, 'selectable': True, 'visible': True,
			'data': {'aggregateMode': 'default', 'source': src + tag.split(']', 1)[-1].lower()},
			'display': {'type': 'line', 'breakLine': True, 'interpolation': 'curveStepAfter' if plot else 'curveLinear', 'radius': 3,
				'styles': {'normal': st(0.9), 'highlighted': st(1), 'muted': st(0.4), 'selected': st(1)}}}
	return [pen('PV', l['pv'], '#1F77B4', 0), pen('SP', l['sp'], '#D62728', 0), pen('Output %', l['cv'], '#2CA02C', 1)]
