# Recipe library for cal1615 (generated by tools/pages.js).
# Recipes are stored as JSON in [cal1615]HMI/recipes: {name: {key: value}}.
# The PLC copies p02_recipe_from_hmi into p01_recipe_active every scan (P02 R04),
# so "download" is simply writing every member to p02_recipe_from_hmi.
LIB = '[cal1615]HMI/recipes'
NAME_WRITE = '[cal1615]p02_recipe_from_hmi/name/name'
# key: (read tag in p01_recipe_active, write tag in p02_recipe_from_hmi)
FIELDS = {
	'zone_1__recirc_sp': ('[cal1615]p01_recipe_active/zone_1/recirc_sp', '[cal1615]p02_recipe_from_hmi/zone_1/recirc_sp'),
	'zone_1__exhaust_sp': ('[cal1615]p01_recipe_active/zone_1/exhaust_sp', '[cal1615]p02_recipe_from_hmi/zone_1/exhaust_sp'),
	'zone_1__temp_sp': ('[cal1615]p01_recipe_active/zone_1/temp_sp', '[cal1615]p02_recipe_from_hmi/zone_1/temp_sp'),
	'zone_2__recirc_sp': ('[cal1615]p01_recipe_active/zone_2/recirc_sp', '[cal1615]p02_recipe_from_hmi/zone_2/recirc_sp'),
	'zone_2__exhaust_sp': ('[cal1615]p01_recipe_active/zone_2/exhaust_sp', '[cal1615]p02_recipe_from_hmi/zone_2/exhaust_sp'),
	'zone_2__temp_sp': ('[cal1615]p01_recipe_active/zone_2/temp_sp', '[cal1615]p02_recipe_from_hmi/zone_2/temp_sp'),
	'zone_3__recirc_sp': ('[cal1615]p01_recipe_active/zone_3/recirc_sp', '[cal1615]p02_recipe_from_hmi/zone_3/recirc_sp'),
	'zone_3__exhaust_sp': ('[cal1615]p01_recipe_active/zone_3/exhaust_sp', '[cal1615]p02_recipe_from_hmi/zone_3/exhaust_sp'),
	'zone_3__temp_sp': ('[cal1615]p01_recipe_active/zone_3/temp_sp', '[cal1615]p02_recipe_from_hmi/zone_3/temp_sp'),
	'line_speed_sp': ('[cal1615]p01_recipe_active/line_speed_sp', '[cal1615]p02_recipe_from_hmi/line_speed_sp'),
	'letoff_tension_sp': ('[cal1615]p01_recipe_active/letoff_tension_sp', '[cal1615]p02_recipe_from_hmi/letoff_tension_sp'),
	'acc_tension_sp': ('[cal1615]p01_recipe_active/acc_tension_sp', '[cal1615]p02_recipe_from_hmi/acc_tension_sp'),
	'acc_fill_pressure_sp': ('[cal1615]p01_recipe_active/acc_fill_pressure_sp', '[cal1615]p02_recipe_from_hmi/acc_fill_pressure_sp'),
	'acc_counter_pressure_sp': ('[cal1615]p01_recipe_active/acc_counter_pressure_sp', '[cal1615]p02_recipe_from_hmi/acc_counter_pressure_sp'),
	'cure_time_sp': ('[cal1615]p01_recipe_active/cure_time_sp', '[cal1615]p02_recipe_from_hmi/cure_time_sp'),
	'platen_temp_sp': ('[cal1615]p01_recipe_active/platen_temp_sp', '[cal1615]p02_recipe_from_hmi/platen_temp_sp'),
	'impreg_gap_sp': ('[cal1615]p01_recipe_active/impreg_gap_sp', '[cal1615]p02_recipe_from_hmi/impreg_gap_sp'),
	'impreg_gap_ds_offset_sp': ('[cal1615]p01_recipe_active/impreg_gap_ds_offset_sp', '[cal1615]p02_recipe_from_hmi/impreg_gap_ds_offset_sp'),
	'impreg_gap_os_offset_sp': ('[cal1615]p01_recipe_active/impreg_gap_os_offset_sp', '[cal1615]p02_recipe_from_hmi/impreg_gap_os_offset_sp'),
	'impreg_supply_speed_sp': ('[cal1615]p01_recipe_active/impreg_supply_speed_sp', '[cal1615]p02_recipe_from_hmi/impreg_supply_speed_sp'),
	'ts1_mode_sp': ('[cal1615]p01_recipe_active/ts1_mode_sp', '[cal1615]p02_recipe_from_hmi/ts1_mode_sp'),
	'ts1_tension_sp': ('[cal1615]p01_recipe_active/ts1_tension_sp', '[cal1615]p02_recipe_from_hmi/ts1_tension_sp'),
	'ts1_stretch_sp': ('[cal1615]p01_recipe_active/ts1_stretch_sp', '[cal1615]p02_recipe_from_hmi/ts1_stretch_sp'),
	'slitter_speed_sp': ('[cal1615]p01_recipe_active/slitter_speed_sp', '[cal1615]p02_recipe_from_hmi/slitter_speed_sp'),
	'adv_cooling_temp_sp': ('[cal1615]p01_recipe_active/adv_cooling_temp_sp', '[cal1615]p02_recipe_from_hmi/adv_cooling_temp_sp'),
	'ts2_tension_sp': ('[cal1615]p01_recipe_active/ts2_tension_sp', '[cal1615]p02_recipe_from_hmi/ts2_tension_sp'),
	'lower_poly_tension_sp': ('[cal1615]p01_recipe_active/lower_poly_tension_sp', '[cal1615]p02_recipe_from_hmi/lower_poly_tension_sp'),
	'lower_poly_b_tension_sp': ('[cal1615]p01_recipe_active/lower_poly_b_tension_sp', '[cal1615]p02_recipe_from_hmi/lower_poly_b_tension_sp'),
	'upper_poly_tension_sp': ('[cal1615]p01_recipe_active/upper_poly_tension_sp', '[cal1615]p02_recipe_from_hmi/upper_poly_tension_sp'),
	'upper_poly_b_tension_sp': ('[cal1615]p01_recipe_active/upper_poly_b_tension_sp', '[cal1615]p02_recipe_from_hmi/upper_poly_b_tension_sp'),
	'winder_tension_sp': ('[cal1615]p01_recipe_active/winder_tension_sp', '[cal1615]p02_recipe_from_hmi/winder_tension_sp'),
	'winder_mode_sp': ('[cal1615]p01_recipe_active/winder_mode_sp', '[cal1615]p02_recipe_from_hmi/winder_mode_sp'),
	'winder_torque_sp': ('[cal1615]p01_recipe_active/winder_torque_sp', '[cal1615]p02_recipe_from_hmi/winder_torque_sp'),
	'tension_deviation_sp': ('[cal1615]p01_recipe_active/tension_deviation_sp', '[cal1615]p02_recipe_from_hmi/tension_deviation_sp'),
}
KEYS = sorted(FIELDS.keys())

def _load():
	v = system.tag.readBlocking([LIB])[0].value
	try:
		return dict(system.util.jsonDecode(v) or {}) if v else {}
	except:
		return {}

def _store(d):
	system.tag.writeBlocking([LIB], [system.util.jsonEncode(d)])

def names():
	return sorted(_load().keys())

def get(name):
	return dict(_load().get(name) or {})

def save(name, values):
	d = _load()
	d[name] = dict((k, float(values.get(k) or 0)) for k in KEYS)
	_store(d)

def delete(name):
	d = _load()
	d.pop(name, None)
	_store(d)

def fromDraft(values):
	"""Plain dict from the session draft (a Perspective property object)."""
	out = {}
	for k in KEYS:
		try:
			out[k] = float(values[k] or 0)
		except:
			out[k] = 0.0
	return out

def readActive():
	qvs = system.tag.readBlocking([FIELDS[k][0] for k in KEYS])
	return dict((k, qv.value) for k, qv in zip(KEYS, qvs))

def download(name, values):
	paths = [FIELDS[k][1] for k in KEYS]
	vals = [float(values.get(k) or 0) for k in KEYS]
	if NAME_WRITE:
		paths.append(NAME_WRITE)
		vals.append(name)
	return system.tag.writeBlocking(paths, vals)
